using DeploySoftware.LaunchPad.Core.Util;
using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a basic class generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public abstract partial class LaunchPadGeneratedClassBase : LaunchPadGeneratedObjectBase
    {
        /// <summary>
        /// Contains information related to this object's position with a Visual Studio solution
        /// </summary>
        public LaunchPadGeneratedVisualStudioClassConfiguration VisualStudioConfig { get; set; }

        /// <summary>
        /// The namespace of the generated item.
        /// </summary>
        public string Namespace { get; set; }

        /// <summary>
        /// The class and interface inheritance of the item (everything after the colon ':' in the definition)
        /// </summary>
        public string InheritsFrom { get; set; }

        /// <summary>
        /// The dictionary of unique base LaunchPad properties that belong to this class (received through DomainEntity or other base class inheritance).
        /// </summary>
        public IDictionary<string, LaunchPadGeneratedProperty> BaseProperties { get; set; }

        /// <summary>
        /// The dictionary of unique custom properties that belong to this class (that were not inherited).
        /// </summary>
        public IDictionary<string, LaunchPadGeneratedProperty> CustomProperties { get; set; }

        public IDictionary<string, LaunchPadGeneratedProperty> Properties => new DictionaryHelper().MergeDictionaries(BaseProperties, CustomProperties);

        /// <summary>
        /// The dictionary of unique base methods that belong to this class 
        /// </summary>
        public IDictionary<string, LaunchPadGeneratedMethod> BaseMethods { get; set; }

        /// <summary>
        /// The dictionary of unique custom methods that belong to this class 
        /// </summary>
        public IDictionary<string, LaunchPadGeneratedMethod> CustomMethods { get; set; }


        public LaunchPadGeneratedClassBase() : base()
        {
            Namespace = string.Empty;
            InheritsFrom = string.Empty;
            var comparer = StringComparer.OrdinalIgnoreCase;
            BaseProperties = new Dictionary<string, LaunchPadGeneratedProperty>(comparer);
            CustomProperties = new Dictionary<string, LaunchPadGeneratedProperty>(comparer);
            BaseMethods = new Dictionary<string, LaunchPadGeneratedMethod>(comparer);
            CustomMethods = new Dictionary<string, LaunchPadGeneratedMethod>(comparer);
            VisualStudioConfig = new LaunchPadGeneratedVisualStudioClassConfiguration();
        }
    }
}
