using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a domain entity class generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedDomainEntity : LaunchPadGeneratedObjectBase
    {
        /// <summary>
        /// Contains information related to this object's position with a Visual Studio solution
        /// </summary>
        public LaunchPadGeneratedVisualStudioClassConfiguration VisualStudioConfig { get; set; }

        /// <summary>
        /// The namespace of the generated item.
        /// </summary>
        public string Namespace { get; set; }

        /// <summary>
        /// The class and interface inheritance of the item (everything after the colon ':' in the definition)
        /// </summary>
        public string InheritsFrom { get; set; }

        /// <summary>
        /// The list of base LaunchPad properties that belong to this class (received through DomainEntity or other base class inheritance).
        /// </summary>
        public IList<LaunchPadGeneratedProperty> BaseProperties { get; set; }

        /// <summary>
        /// The list of custom properties that belong to this class (that were not inherited).
        /// </summary>
        public IList<LaunchPadGeneratedProperty> CustomProperties { get; set; }

        /// <summary>
        /// The list of base methods that belong to this class (received through DomainEntity or other base class inheritance).
        /// </summary>
        public IList<LaunchPadGeneratedMethod> BaseMethods { get; set; }

        /// <summary>
        /// The list of custom methods that belong to this class (that were not inherited).
        /// </summary>
        public IList<LaunchPadGeneratedMethod> CustomMethods { get; set; }

        public LaunchPadGeneratedDomainEntity() : base()
        {
            Namespace = string.Empty;
            InheritsFrom = string.Empty;
            BaseProperties = new List<LaunchPadGeneratedProperty>();
            CustomProperties = new List<LaunchPadGeneratedProperty>();
            BaseMethods = new List<LaunchPadGeneratedMethod>();
            CustomMethods = new List<LaunchPadGeneratedMethod>();
            VisualStudioConfig = new LaunchPadGeneratedVisualStudioClassConfiguration();
        }
    }
}
