using System;
using System.Collections.Generic;
using System.Text;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a C# DTO generated by LaunchPad Framework.
    /// </summary>
    [Serializable]
    public partial class LaunchPadGeneratedDataTransferObject : LaunchPadGeneratedObjectBase
    {
        
        /// <summary>
        /// Contains information related to this object's position with a Visual Studio solution
        /// </summary>
        public LaunchPadGeneratedVisualStudioClassConfiguration VisualStudioConfig { get; set; }

        /// <summary>
        /// The list of base properties that belong to this DTO (which may be identical to the domain entity, or not)
        /// </summary>
        public IList<LaunchPadGeneratedProperty> BaseProperties { get; set; }

        /// <summary>
        /// The list of custom properties that belong to this DTO (which may be identical to the domain entity, or not)
        /// </summary>
        public IList<LaunchPadGeneratedProperty> CustomProperties { get; set; }

        /// <summary>
        /// The namespace of the generated item.
        /// </summary>
        public string Namespace { get; set; }

        /// <summary>
        /// The class and interface inheritance of the item (everything after the colon ':' in the definition)
        /// </summary>
        public string InheritsFrom { get; set; }

        /// <summary>
        /// The ID of the property set which applies to this DTO
        /// </summary>
        public string PropertySetId { get; set; }

        public LaunchPadGeneratedDataTransferObject() : base()
        {
            Annotations = string.Empty;
            Namespace = string.Empty;
            InheritsFrom = string.Empty;
            BaseProperties = new List<LaunchPadGeneratedProperty>();
            CustomProperties = new List<LaunchPadGeneratedProperty>();
            VisualStudioConfig = new LaunchPadGeneratedVisualStudioClassConfiguration();
            PropertySetId = string.Empty;
        }
    }
}
