using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a domain entity class generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedDomainEntity : LaunchPadGeneratedClassBase
    {
       
        /// <summary>
        /// Contains a collection of Data Transfer Objects belonging to this component
        /// </summary>
        public IDictionary<string, LaunchPadGeneratedDataTransferObject> DataTransferObjects { get; set; }

        public LaunchPadGeneratedDomainEntity() : base()
        {
            var comparer = StringComparer.OrdinalIgnoreCase;
            DataTransferObjects = new Dictionary<string, LaunchPadGeneratedDataTransferObject>(comparer);
        }
    }
}
