using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a dynamic Angular web page generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedAngularWebPage : LaunchPadGeneratedObjectBase
    {


        public LaunchPadGeneratedAngularWebPage() : base()
        {
           
        }
    }
}
