using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a dynamic Angular module generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedAngularModule : LaunchPadGeneratedObjectBase
    {


        public LaunchPadGeneratedAngularModule() : base()
        {
           
        }
    }
}
