using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a Visual Studio component generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedVisualStudioComponent : LaunchPadGeneratedComponentBase
    {
        /// <summary>
        /// Contains information related to this object's position with a Visual Studio solution
        /// </summary>
        public LaunchPadGeneratedVisualStudioComponentConfiguration VisualStudioConfig { get; set; }

        /// <summary>
        /// Contains a dictionary of Property Sets belonging to this component, keyed by the property set id
        /// </summary>
        public IDictionary<string, LaunchPadGeneratedDtoPropertySet> PropertySets { get; set; }

        
        /// <summary>
        /// The list of domain entities that belong to this component.
        /// </summary>
        public IList<LaunchPadGeneratedDomainEntity> DomainEntities { get; set; }

        public LaunchPadGeneratedVisualStudioComponent() : base()
        {
            DomainEntities = new List<LaunchPadGeneratedDomainEntity>();
            var comparer = StringComparer.OrdinalIgnoreCase;
            PropertySets = new Dictionary<string,LaunchPadGeneratedDtoPropertySet>(comparer);
            VisualStudioConfig = new LaunchPadGeneratedVisualStudioComponentConfiguration();
        }
    }
}
