using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a Visual Studio component generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedVisualStudioComponent : LaunchPadGeneratedComponentBase
    {
        /// <summary>
        /// Contains information related to this object's position with a Visual Studio solution
        /// </summary>
        public LaunchPadGeneratedVisualStudioComponentConfiguration VisualStudioConfig { get; set; }

        /// <summary>
        /// Contains a dictionary of Property Sets belonging to this component, keyed by the property set id
        /// </summary>
        public IDictionary<string, LaunchPadGeneratedDtoPropertySet> PropertySets { get; set; }

        /// <summary>
        /// Contains a dictionary of Application Services belonging to this component, keyed by the application service name
        /// </summary>
        public IDictionary<string, LaunchPadGeneratedApplicationService> ApplicationServices { get; set; } 
         

        /// <summary>
        /// Contains a dictionary of Domain Entities belonging to this component, keyed by the domain entity name
        /// </summary>
        public IDictionary<string, LaunchPadGeneratedDomainEntity> DomainEntities { get; set; }

        public LaunchPadGeneratedVisualStudioComponent() : base()
        {
            var comparer = StringComparer.OrdinalIgnoreCase;
            DomainEntities = new Dictionary<string, LaunchPadGeneratedDomainEntity>(comparer);
            ApplicationServices = new Dictionary<string, LaunchPadGeneratedApplicationService>(comparer); 
            PropertySets = new Dictionary<string,LaunchPadGeneratedDtoPropertySet>(comparer);
            VisualStudioConfig = new LaunchPadGeneratedVisualStudioComponentConfiguration();
        }
    }
}
