using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a static css file generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedStaticStylesheet : LaunchPadGeneratedObjectBase
    {

        public LaunchPadGeneratedStaticStylesheet() : base()
        {
           
        }
    }
}
