using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a Visual Studio component generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedVisualStudioComponent : LaunchPadGeneratedComponentBase
    {
        /// <summary>
        /// Contains information related to this object's position with a Visual Studio solution
        /// </summary>
        public LaunchPadGeneratedVisualStudioComponentConfiguration VisualStudioConfig { get; set; }


        /// <summary>
        /// The list of domain entities that belong to this component (if any).
        /// </summary>
        public IList<LaunchPadGeneratedClass> DomainEntities { get; set; }

        public LaunchPadGeneratedVisualStudioComponent() : base()
        {
            DomainEntities = new List<LaunchPadGeneratedClass>();
            VisualStudioConfig = new LaunchPadGeneratedVisualStudioComponentConfiguration();
        }
    }
}
