using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a solution generated by LaunchPad Framework which only contains documents.
    /// </summary>
    [Serializable]
    public partial class LaunchPadGeneratedDocumentSolution : LaunchPadGeneratedSolutionBase
    {
        
        /// <summary>
        /// The list of generated document set modules that belong to this solution.
        /// </summary>
        public IList<LaunchPadGeneratedDocumentSetModule> DocumentSetModules { get; set; }

        public LaunchPadGeneratedDocumentSolution() : base()
        {
            Version = string.Empty;
            DocumentSetModules = new List<LaunchPadGeneratedDocumentSetModule>();
        }
    }
}
