using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents an office document (Word, Excel, Powerpoint, RTF) generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedDocument : LaunchPadGeneratedObjectBase
    {


        public LaunchPadGeneratedDocument() : base()
        {
           
        }
    }
}
