using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a solution generated by LaunchPad Framework which only contains documents.
    /// </summary>
    [Serializable]
    public partial class LaunchPadGeneratedDocumentSolution : LaunchPadGeneratedSolutionBase
    {
        /// <summary>
        /// Contains configuration information related to this object's solution
        /// </summary>
        public new LaunchPadGeneratedDocumentSolutionConfiguration Config { get; set; }

        /// <summary>
        /// The dictionary of generated document set modules that belong to this solution.
        /// </summary>
        public virtual IDictionary<string,LaunchPadGeneratedDocumentSetModule> DocumentSetModules { get; set; }

        public LaunchPadGeneratedDocumentSolution() : base()
        {
            Config = new LaunchPadGeneratedDocumentSolutionConfiguration();
            var comparer = StringComparer.OrdinalIgnoreCase;
            DocumentSetModules = new Dictionary<string, LaunchPadGeneratedDocumentSetModule>(comparer);
        }
    }
}
