using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents an office document (Word, Excel, Powerpoint, RTF) generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedDocument : LaunchPadGeneratedObjectBase
    {
        public string MimeType { get; set; }

        public string Extension { get; set; }

        public string FileLocation { get; set; }

        public LaunchPadGeneratedDocument() : base()
        {
            MimeType = string.Empty;
            Extension = string.Empty;
            FileLocation = string.Empty;
        }
    }
}
