using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a set of related documents (Office document (Word, Excel, Powerpoint, RTF) generated by LaunchPad Framework.
    /// </summary>
    public partial class LaunchPadGeneratedDocumentSetModule : LaunchPadGeneratedModuleBase
    {

        /// <summary>
        /// The list of documents that belong to this module.
        /// </summary>
        public IList<LaunchPadGeneratedDocument> Documents { get; set; }

        public LaunchPadGeneratedDocumentSetModule() : base()
        {
            Version = string.Empty;
            Documents = new List<LaunchPadGeneratedDocument>();
        }

    }
}
