using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents an office document (Word, Excel, Powerpoint, RTF) generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedDocument : LaunchPadGeneratedObjectBase
    {
        public string MimeType { get; set; }

        public string Extension { get; set; }

        public string FileLocation { get; set; }

        /// <summary>
        /// Contains information on the template(s) that should be used to generate this document (if any).
        /// If none are listed, templates may be applied if listed in the parent Document Set Module (again, if listed).
        /// </summary>
        public LaunchPadGeneratedDocumentTemplates Templates { get; set; }

        public LaunchPadGeneratedDocument() : base()
        {
            MimeType = string.Empty;
            Extension = string.Empty;
            FileLocation = string.Empty;
            Templates = new LaunchPadGeneratedDocumentTemplates();
        }
    }
}
