//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deploy.LaunchPad.Util {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Deploy_LaunchPad_Util_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Deploy_LaunchPad_Util_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Deploy.LaunchPad.Util.Deploy.LaunchPad.Util.Resources", typeof(Deploy_LaunchPad_Util_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string is {0}..
        /// </summary>
        public static string Debug_GetDbConnectionStringFromSecret {
            get {
                return ResourceManager.GetString("Debug_GetDbConnectionStringFromSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to clear session state for session {1}.
        /// </summary>
        public static string Debug_HttpSessionState_Clear {
            get {
                return ResourceManager.GetString("Debug_HttpSessionState_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to get {0} from session state for session {1}.
        /// </summary>
        public static string Debug_HttpSessionState_Get {
            get {
                return ResourceManager.GetString("Debug_HttpSessionState_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to put {0} to session state for session {1}.
        /// </summary>
        public static string Debug_HttpSessionState_Put {
            get {
                return ResourceManager.GetString("Debug_HttpSessionState_Put", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to remove {0} from session state for session {1}.
        /// </summary>
        public static string Debug_HttpSessionState_Remove {
            get {
                return ResourceManager.GetString("Debug_HttpSessionState_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New instance of TransactionManager with Id {0} created..
        /// </summary>
        public static string Debug_TransactionManager_TransactionManager {
            get {
                return ResourceManager.GetString("Debug_TransactionManager_TransactionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a new TransactionScope with TransactionScopeOption.Required.
        /// </summary>
        public static string Debug_TransactionScopeHelper_CreateScope_with_TransactionScopeOption_Required {
            get {
                return ResourceManager.GetString("Debug_TransactionScopeHelper_CreateScope_with_TransactionScopeOption_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a new TransactionScope with TransactionScopeOption.RequiresNew.
        /// </summary>
        public static string Debug_TransactionScopeHelper_CreateScope_with_TransactionScopeOption_RequiresNew {
            get {
                return ResourceManager.GetString("Debug_TransactionScopeHelper_CreateScope_with_TransactionScopeOption_RequiresNew", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating a new TransactionScope with TransactionScopeOption.Supress.
        /// </summary>
        public static string Debug_TransactionScopeHelper_CreateScope_with_TransactionScopeOption_Suppress {
            get {
                return ResourceManager.GetString("Debug_TransactionScopeHelper_CreateScope_with_TransactionScopeOption_Suppress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid ITransactionManager found in Local state. Creating a new TransactionManager..
        /// </summary>
        public static string Debug_UnitOfWorkManager_DefaultTransactionManager_CreatingNewTransactionManager {
            get {
                return ResourceManager.GetString("Debug_UnitOfWorkManager_DefaultTransactionManager_CreatingNewTransactionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using default UnitOfWorkManager provider to resolve current transaction manager..
        /// </summary>
        public static string Debug_UnitOfWorkManager_DefaultTransactionManager_UsingDefaultProvider {
            get {
                return ResourceManager.GetString("Debug_UnitOfWorkManager_DefaultTransactionManager_UsingDefaultProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction manager provider is being overriden. Using supplied transaction manager provider..
        /// </summary>
        public static string Debug_UnitOfWorkManager_SetTransactionManagerProvider_ProviderBeingOverriden {
            get {
                return ResourceManager.GetString("Debug_UnitOfWorkManager_SetTransactionManagerProvider_ProviderBeingOverriden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction manager provide is being set to null. Using the transaction manager to the default transaction manager provider..
        /// </summary>
        public static string Debug_UnitOfWorkManager_SetTransactionManagerProvider_SetToNull {
            get {
                return ResourceManager.GetString("Debug_UnitOfWorkManager_SetTransactionManagerProvider_SetToNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitOfWorkScope {0} Commiting..
        /// </summary>
        public static string Debug_UnitOfWorkScope_OnCommit {
            get {
                return ResourceManager.GetString("Debug_UnitOfWorkScope_OnCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitOfWorkScope {0} Rolling back..
        /// </summary>
        public static string Debug_UnitOfWorkScope_OnRollback {
            get {
                return ResourceManager.GetString("Debug_UnitOfWorkScope_OnRollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist..
        /// </summary>
        public static string Exception_DirectoryInfo_Not_Exists {
            get {
                return ResourceManager.GetString("Exception_DirectoryInfo_Not_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scope being committed is not attached to the current transaction..
        /// </summary>
        public static string Exception_UnitOfWorkTransaction_OnScopeCommitting_InvalidOperationException {
            get {
                return ResourceManager.GetString("Exception_UnitOfWorkTransaction_OnScopeCommitting_InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should not throw FormatException due to DateString.
        /// </summary>
        public static string Guard_GeographicLocation_Instantiate_FormatException {
            get {
                return ResourceManager.GetString("Guard_GeographicLocation_Instantiate_FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude must be a valid decimal number..
        /// </summary>
        public static string Guard_GeographicLocation_Set_Altitude {
            get {
                return ResourceManager.GetString("Guard_GeographicLocation_Set_Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation must be a valid decimal number..
        /// </summary>
        public static string Guard_GeographicLocation_Set_Elevation {
            get {
                return ResourceManager.GetString("Guard_GeographicLocation_Set_Elevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value was either too large or too small for a Decimal..
        /// </summary>
        public static string Guard_GeographicLocation_Set_Latitude_NaN {
            get {
                return ResourceManager.GetString("Guard_GeographicLocation_Set_Latitude_NaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitudinal coordinate decimal cannot be greater than 90.
        /// </summary>
        public static string Guard_GeographicLocation_Set_Latitude_Not_GreaterThan_90 {
            get {
                return ResourceManager.GetString("Guard_GeographicLocation_Set_Latitude_Not_GreaterThan_90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitudinal coordinate decimal cannot be less than 90..
        /// </summary>
        public static string Guard_GeographicLocation_Set_Latitude_Not_LessThan_Minus_90 {
            get {
                return ResourceManager.GetString("Guard_GeographicLocation_Set_Latitude_Not_LessThan_Minus_90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value was either too large or too small for a Decimal..
        /// </summary>
        public static string Guard_GeographicLocation_Set_Longitude_NaN {
            get {
                return ResourceManager.GetString("Guard_GeographicLocation_Set_Longitude_NaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitudinal coordinate decimal cannot be greater than 180..
        /// </summary>
        public static string Guard_GeographicLocation_Set_Longitude_Not_GreaterThan_180 {
            get {
                return ResourceManager.GetString("Guard_GeographicLocation_Set_Longitude_Not_GreaterThan_180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitudinal coordinate decimal cannot be less than 180..
        /// </summary>
        public static string Guard_GeographicLocation_Set_Longitude_Not_LessThan_Minus180 {
            get {
                return ResourceManager.GetString("Guard_GeographicLocation_Set_Longitude_Not_LessThan_Minus180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitudinal coordinate decimal cannot be more than 180..
        /// </summary>
        public static string Guard_GeographicLocation_Set_Longitude_Not_MoreThan_180 {
            get {
                return ResourceManager.GetString("Guard_GeographicLocation_Set_Longitude_Not_MoreThan_180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Results must be -1 or a positive number..
        /// </summary>
        public static string Guard_InMemoryRepository_ConstrainQueryInput_MaxResult_Equals0 {
            get {
                return ResourceManager.GetString("Guard_InMemoryRepository_ConstrainQueryInput_MaxResult_Equals0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Results must be -1 or a positive number..
        /// </summary>
        public static string Guard_InMemoryRepository_ConstrainQueryInput_MaxResult_LessThanMinus1 {
            get {
                return ResourceManager.GetString("Guard_InMemoryRepository_ConstrainQueryInput_MaxResult_LessThanMinus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query parameter cannot be null..
        /// </summary>
        public static string Guard_InMemoryRepository_ConstrainQueryInput_Query_IsNull {
            get {
                return ResourceManager.GetString("Guard_InMemoryRepository_ConstrainQueryInput_Query_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Result must be greater than or equal to zero..
        /// </summary>
        public static string Guard_InMemoryRepository_ConstrainQueryInput_StartResult_LessThan0 {
            get {
                return ResourceManager.GetString("Guard_InMemoryRepository_ConstrainQueryInput_StartResult_LessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key must not be null..
        /// </summary>
        public static string Guard_InMemoryRepository_GetByKey_Key_IsNull {
            get {
                return ResourceManager.GetString("Guard_InMemoryRepository_GetByKey_Key_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is null.
        /// </summary>
        public static string Guard_Input_IsNull {
            get {
                return ResourceManager.GetString("Guard_Input_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string is null or empty.
        /// </summary>
        public static string Guard_Input_IsNullOrEmpty {
            get {
                return ResourceManager.GetString("Guard_Input_IsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token string cannot be empty or null..
        /// </summary>
        public static string Guard_LaunchPadToken_ArgumentException_Empty {
            get {
                return ResourceManager.GetString("Guard_LaunchPadToken_ArgumentException_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token string must contain a name section, beginning with &apos;n:&apos;..
        /// </summary>
        public static string Guard_LaunchPadToken_ArgumentException_MissingName {
            get {
                return ResourceManager.GetString("Guard_LaunchPadToken_ArgumentException_MissingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token string must contain a prefix section, beginning with &apos;p:&apos;..
        /// </summary>
        public static string Guard_LaunchPadToken_ArgumentException_MissingPrefix {
            get {
                return ResourceManager.GetString("Guard_LaunchPadToken_ArgumentException_MissingPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token string must contain at least two sections, delimited by &apos;|&apos;..
        /// </summary>
        public static string Guard_LaunchPadToken_ArgumentException_NoDelimiter {
            get {
                return ResourceManager.GetString("Guard_LaunchPadToken_ArgumentException_NoDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token string must end with &apos;}}&apos; characters..
        /// </summary>
        public static string Guard_LaunchPadToken_ArgumentException_WrongEndWith {
            get {
                return ResourceManager.GetString("Guard_LaunchPadToken_ArgumentException_WrongEndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token string must contain only two (2) to five (5) sections, delimited by &apos;|&apos;..
        /// </summary>
        public static string Guard_LaunchPadToken_ArgumentException_WrongNumberSections {
            get {
                return ResourceManager.GetString("Guard_LaunchPadToken_ArgumentException_WrongNumberSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token string must start with &apos;{{&apos; characters..
        /// </summary>
        public static string Guard_LaunchPadToken_ArgumentException_WrongStartsWith {
            get {
                return ResourceManager.GetString("Guard_LaunchPadToken_ArgumentException_WrongStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Text cannot be empty or null..
        /// </summary>
        public static string Guard_LaunchPadTokenizer_ArgumentException_OriginalText {
            get {
                return ResourceManager.GetString("Guard_LaunchPadTokenizer_ArgumentException_OriginalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one token must be provided..
        /// </summary>
        public static string Guard_LaunchPadTokenizer_ArgumentException_Tokens {
            get {
                return ResourceManager.GetString("Guard_LaunchPadTokenizer_ArgumentException_Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No compatible UnitOfWork was found. Please start a compatible UnitOfWorkScope before using the repository..
        /// </summary>
        public static string Guard_RepositoryBase_UnitOfWork_NoCompatibleTypeFound {
            get {
                return ResourceManager.GetString("Guard_RepositoryBase_UnitOfWork_NoCompatibleTypeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current UnitOfWork instance is not compatible with the repository. Please start a compatible unit of work before using the repository..
        /// </summary>
        public static string Guard_RepositoryBase_UnitOfWork_NotCompatibleType {
            get {
                return ResourceManager.GetString("Guard_RepositoryBase_UnitOfWork_NotCompatibleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a non null expression as a predicate for the specification..
        /// </summary>
        public static string Guard_Specification_Specification {
            get {
                return ResourceManager.GetString("Guard_Specification_Specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This unit of work scope has been marked completed. A child scope participating in the transaction has rolledback and the transaction aborted. The parent scope cannot be commit..
        /// </summary>
        public static string Guard_UnitOfWorkScope_Commit_InvalidOperationException {
            get {
                return ResourceManager.GetString("Guard_UnitOfWorkScope_Commit_InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot commit a disposed UnitOfWorkScope instance..
        /// </summary>
        public static string Guard_UnitOfWorkScope_Commit_ObjectDisposedException {
            get {
                return ResourceManager.GetString("Guard_UnitOfWorkScope_Commit_ObjectDisposedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No compatible UnitOfWork was found. Please start a compatible UnitOfWorkScope before using the repository..
        /// </summary>
        public static string Guard_UnitOfWorkScope_CurrentUnitOfWork_NoCompatibleTypeFound {
            get {
                return ResourceManager.GetString("Guard_UnitOfWorkScope_CurrentUnitOfWork_NoCompatibleTypeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current unit of work is not compatible with expected type {0}, instead the current unit of work is of type {1}..
        /// </summary>
        public static string Guard_UnitOfWorkScope_CurrentUnitOfWork_NotCompatibleType {
            get {
                return ResourceManager.GetString("Guard_UnitOfWorkScope_CurrentUnitOfWork_NotCompatibleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a non-null IUnitOfWorkScope instance..
        /// </summary>
        public static string Guard_UnitOfWorkTransaction_EnlistScope_ArgumentNullException {
            get {
                return ResourceManager.GetString("Guard_UnitOfWorkTransaction_EnlistScope_ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction attached to the scope has already been disposed..
        /// </summary>
        public static string Guard_UnitOfWorkTransaction_OnScopeCommitting_ObjectDisposedException {
            get {
                return ResourceManager.GetString("Guard_UnitOfWorkTransaction_OnScopeCommitting_ObjectDisposedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction attached to the scope has already been disposed..
        /// </summary>
        public static string Guard_UnitOfWorkTransaction_OnScopeRollingBack_ObjectDisposedException {
            get {
                return ResourceManager.GetString("Guard_UnitOfWorkTransaction_OnScopeRollingBack_ObjectDisposedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a non-null TransactionScope instance..
        /// </summary>
        public static string Guard_UnitOfWorkTransaction_UnitOfWorkTransaction_ArgumentNullException_transaction {
            get {
                return ResourceManager.GetString("Guard_UnitOfWorkTransaction_UnitOfWorkTransaction_ArgumentNullException_transacti" +
                        "on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a non-null UnitOfWork instance..
        /// </summary>
        public static string Guard_UnitOfWorkTransaction_UnitOfWorkTransaction_ArgumentNullException_unitOfWork {
            get {
                return ResourceManager.GetString("Guard_UnitOfWorkTransaction_UnitOfWorkTransaction_ArgumentNullException_unitOfWor" +
                        "k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute name cannot be null or empty..
        /// </summary>
        public static string Guard_Xml_AttributeName_Is_Null {
            get {
                return ResourceManager.GetString("Guard_Xml_AttributeName_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node cannot be null..
        /// </summary>
        public static string Guard_Xml_Node_Is_Null {
            get {
                return ResourceManager.GetString("Guard_Xml_Node_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertySetsNodes collection is null or empty..
        /// </summary>
        public static string Guard_Xml_PropertySetsNodes_Is_Null {
            get {
                return ResourceManager.GetString("Guard_Xml_PropertySetsNodes_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPath cannot be null or empty..
        /// </summary>
        public static string Guard_Xml_XPath_Is_NullOrEmpty {
            get {
                return ResourceManager.GetString("Guard_Xml_XPath_Is_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposing of transaction manager {0}..
        /// </summary>
        public static string Info_TransactionManager_Dispose {
            get {
                return ResourceManager.GetString("Info_TransactionManager_Dispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlisting scope {0} with transaction manager {1} with transaction mode {2}..
        /// </summary>
        public static string Info_TransactionManager_EnlistScope_EnlistingScope {
            get {
                return ResourceManager.GetString("Info_TransactionManager_EnlistScope_EnlistingScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlisting scope {0} with mode {1} requires a new TransactionScope to be created..
        /// </summary>
        public static string Info_TransactionManager_EnlistScope_EnlistingScopeRequiresNewTransactionScope {
            get {
                return ResourceManager.GetString("Info_TransactionManager_EnlistScope_EnlistingScopeRequiresNewTransactionScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitOfWorkTransaction {0} signalled a disposed. Unregistering transaction from TransactionManager {1}..
        /// </summary>
        public static string Info_TransactionManager_OnTransactionDisposing {
            get {
                return ResourceManager.GetString("Info_TransactionManager_OnTransactionDisposing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposing off transction {0}..
        /// </summary>
        public static string Info_UnitOfWorkTransaction_Dispose_Disposing {
            get {
                return ResourceManager.GetString("Info_UnitOfWorkTransaction_Dispose_Disposing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope {0} enlisted with transaction {1}..
        /// </summary>
        public static string Info_UnitOfWorkTransaction_EnlistScope_Enlisted {
            get {
                return ResourceManager.GetString("Info_UnitOfWorkTransaction_EnlistScope_Enlisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All scopes have signalled a commit on transaction {0}. Flushing unit of work and commiting attached TransactionScope..
        /// </summary>
        public static string Info_UnitOfWorkTransaction_OnScopeCommitting_Committing {
            get {
                return ResourceManager.GetString("Info_UnitOfWorkTransaction_OnScopeCommitting_Committing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit signalled by scope {0} on transaction {1}..
        /// </summary>
        public static string Info_UnitOfWorkTransaction_OnScopeCommitting_Signalled {
            get {
                return ResourceManager.GetString("Info_UnitOfWorkTransaction_OnScopeCommitting_Signalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaching all scopes and disposing of attached TransactionScope on transaction {0}..
        /// </summary>
        public static string Info_UnitOfWorkTransaction_OnScopeRollingBack_Disposing {
            get {
                return ResourceManager.GetString("Info_UnitOfWorkTransaction_OnScopeRollingBack_Disposing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback signalled by scope {0} on transaction {1}..
        /// </summary>
        public static string Info_UnitOfWorkTransaction_OnScopeRollingBack_Signalled {
            get {
                return ResourceManager.GetString("Info_UnitOfWorkTransaction_OnScopeRollingBack_Signalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New UnitOfWorkTransction created with Id {0}..
        /// </summary>
        public static string Info_UnitOfWorkTransaction_UnitOfWorkTransaction_Created {
            get {
                return ResourceManager.GetString("Info_UnitOfWorkTransaction_UnitOfWorkTransaction_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item &quot;{0}&quot; was added to the collection..
        /// </summary>
        public static string Logger_Info_ItemAdded {
            get {
                return ResourceManager.GetString("Logger_Info_ItemAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item &quot;{0}&quot; already exists in the collection..
        /// </summary>
        public static string Logger_Info_ItemAlreadyExists {
            get {
                return ResourceManager.GetString("Logger_Info_ItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item &quot;{0}&quot; already existed in the collection, overwrote it with new value..
        /// </summary>
        public static string Logger_Info_ItemAlreadyExistsOverwriting {
            get {
                return ResourceManager.GetString("Logger_Info_ItemAlreadyExistsOverwriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Government is about making government more accessible to everyone. 
        ///                                        This means giving greater access to government data and information to the Canadian public and the businesses community. 
        ///                                        The Information Provider grants you a worldwide, royalty-free, perpetual, non-exclusive licence to use the Information, 
        ///                                        including for commercial purposes, subject to the license terms. 
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Text_OpenGovernmentCanadaLicense_LicenseDescription {
            get {
                return ResourceManager.GetString("Text_OpenGovernmentCanadaLicense_LicenseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Government License - Canada.
        /// </summary>
        public static string Text_OpenGovernmentCanadaLicense_LicenseName {
            get {
                return ResourceManager.GetString("Text_OpenGovernmentCanadaLicense_LicenseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://open.canada.ca/en/open-government-licence-canada.
        /// </summary>
        public static string Text_OpenGovernmentCanadaLicense_LicenseTerms {
            get {
                return ResourceManager.GetString("Text_OpenGovernmentCanadaLicense_LicenseTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlation ID field must be 36 characters or less..
        /// </summary>
        public static string Validation_CorrelationId_36CharsOrLess {
            get {
                return ResourceManager.GetString("Validation_CorrelationId_36CharsOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture must be 5 characters or less..
        /// </summary>
        public static string Validation_Culture_5CharsOrLess {
            get {
                return ResourceManager.GetString("Validation_Culture_5CharsOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Full must be 8096 characters or less..
        /// </summary>
        public static string Validation_DescriptionFull_8096CharsOrLess {
            get {
                return ResourceManager.GetString("Validation_DescriptionFull_8096CharsOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Short must be 256 characters or less..
        /// </summary>
        public static string Validation_DescriptionShort_256CharsOrLess {
            get {
                return ResourceManager.GetString("Validation_DescriptionShort_256CharsOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External ID field must be 36 characters or less..
        /// </summary>
        public static string Validation_ExternalId_36CharsOrLess {
            get {
                return ResourceManager.GetString("Validation_ExternalId_36CharsOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be 100 characters or less..
        /// </summary>
        public static string Validation_Name_100CharsOrLess {
            get {
                return ResourceManager.GetString("Validation_Name_100CharsOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be 256 characters or less..
        /// </summary>
        public static string Validation_Name_256CharsOrLess {
            get {
                return ResourceManager.GetString("Validation_Name_256CharsOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token name must be 20 characters or less..
        /// </summary>
        public static string Validation_Token_Name_20CharsOrLess {
            get {
                return ResourceManager.GetString("Validation_Token_Name_20CharsOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token prefix must be 9 characters or less..
        /// </summary>
        public static string Validation_Token_Prefix_9CharsOrLess {
            get {
                return ResourceManager.GetString("Validation_Token_Prefix_9CharsOrLess", resourceCulture);
            }
        }
    }
}
