// ***********************************************************************
// Assembly         : Deploy.LaunchPad.Core
// Author           : Nicholas Kellett
// Created          : 11-19-2023
//
// Last Modified By : Nicholas Kellett
// Last Modified On : 07-26-2023
// ***********************************************************************
// <copyright file="Deploy.LaunchPad.Core.Resources.Designer.cs" company="Deploy Software Solutions, inc.">
//     2018-2023 Deploy Software Solutions, inc.
// </copyright>
// <summary></summary>
// ***********************************************************************

namespace Deploy.LaunchPad.Core {
    using System;


    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Deploy_LaunchPad_Core_Resources {

        /// <summary>
        /// The resource man
        /// </summary>
        private static global::System.Resources.ResourceManager resourceMan;

        /// <summary>
        /// The resource culture
        /// </summary>
        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Initializes a new instance of the <see cref="Deploy_LaunchPad_Core_Resources"/> class.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Deploy_LaunchPad_Core_Resources() {
        }

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        /// <value>The resource manager.</value>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Deploy.LaunchPad.Core.Deploy.LaunchPad.Core.Resources", typeof(Deploy_LaunchPad_Core_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        /// <value>The culture.</value>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Connection string is {0}..
        /// </summary>
        /// <value>The debug get database connection string from secret.</value>
        public static string Debug_GetDbConnectionStringFromSecret {
            get {
                return ResourceManager.GetString("Debug_GetDbConnectionStringFromSecret", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Attempting to clear session state for session {1}.
        /// </summary>
        /// <value>The debug HTTP session state clear.</value>
        public static string Debug_HttpSessionState_Clear {
            get {
                return ResourceManager.GetString("Debug_HttpSessionState_Clear", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Attempting to get {0} from session state for session {1}.
        /// </summary>
        /// <value>The debug HTTP session state get.</value>
        public static string Debug_HttpSessionState_Get {
            get {
                return ResourceManager.GetString("Debug_HttpSessionState_Get", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Attempting to put {0} to session state for session {1}.
        /// </summary>
        /// <value>The debug HTTP session state put.</value>
        public static string Debug_HttpSessionState_Put {
            get {
                return ResourceManager.GetString("Debug_HttpSessionState_Put", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Attempting to remove {0} from session state for session {1}.
        /// </summary>
        /// <value>The debug HTTP session state remove.</value>
        public static string Debug_HttpSessionState_Remove {
            get {
                return ResourceManager.GetString("Debug_HttpSessionState_Remove", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to New instance of TransactionManager with Id {0} created..
        /// </summary>
        /// <value>The debug transaction manager transaction manager.</value>
        public static string Debug_TransactionManager_TransactionManager {
            get {
                return ResourceManager.GetString("Debug_TransactionManager_TransactionManager", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Creating a new TransactionScope with TransactionScopeOption.Required.
        /// </summary>
        /// <value>The debug transaction scope helper create scope with transaction scope option required.</value>
        public static string Debug_TransactionScopeHelper_CreateScope_with_TransactionScopeOption_Required {
            get {
                return ResourceManager.GetString("Debug_TransactionScopeHelper_CreateScope_with_TransactionScopeOption_Required", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Creating a new TransactionScope with TransactionScopeOption.RequiresNew.
        /// </summary>
        /// <value>The debug transaction scope helper create scope with transaction scope option requires new.</value>
        public static string Debug_TransactionScopeHelper_CreateScope_with_TransactionScopeOption_RequiresNew {
            get {
                return ResourceManager.GetString("Debug_TransactionScopeHelper_CreateScope_with_TransactionScopeOption_RequiresNew", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Creating a new TransactionScope with TransactionScopeOption.Supress.
        /// </summary>
        /// <value>The debug transaction scope helper create scope with transaction scope option suppress.</value>
        public static string Debug_TransactionScopeHelper_CreateScope_with_TransactionScopeOption_Suppress {
            get {
                return ResourceManager.GetString("Debug_TransactionScopeHelper_CreateScope_with_TransactionScopeOption_Suppress", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to No valid ITransactionManager found in Local state. Creating a new TransactionManager..
        /// </summary>
        /// <value>The debug unit of work manager default transaction manager creating new transaction manager.</value>
        public static string Debug_UnitOfWorkManager_DefaultTransactionManager_CreatingNewTransactionManager {
            get {
                return ResourceManager.GetString("Debug_UnitOfWorkManager_DefaultTransactionManager_CreatingNewTransactionManager", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Using default UnitOfWorkManager provider to resolve current transaction manager..
        /// </summary>
        /// <value>The debug unit of work manager default transaction manager using default provider.</value>
        public static string Debug_UnitOfWorkManager_DefaultTransactionManager_UsingDefaultProvider {
            get {
                return ResourceManager.GetString("Debug_UnitOfWorkManager_DefaultTransactionManager_UsingDefaultProvider", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to The transaction manager provider is being overriden. Using supplied transaction manager provider..
        /// </summary>
        /// <value>The debug unit of work manager set transaction manager provider provider being overriden.</value>
        public static string Debug_UnitOfWorkManager_SetTransactionManagerProvider_ProviderBeingOverriden {
            get {
                return ResourceManager.GetString("Debug_UnitOfWorkManager_SetTransactionManagerProvider_ProviderBeingOverriden", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to The transaction manager provide is being set to null. Using the transaction manager to the default transaction manager provider..
        /// </summary>
        /// <value>The debug unit of work manager set transaction manager provider set to null.</value>
        public static string Debug_UnitOfWorkManager_SetTransactionManagerProvider_SetToNull {
            get {
                return ResourceManager.GetString("Debug_UnitOfWorkManager_SetTransactionManagerProvider_SetToNull", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to UnitOfWorkScope {0} Commiting..
        /// </summary>
        /// <value>The debug unit of work scope on commit.</value>
        public static string Debug_UnitOfWorkScope_OnCommit {
            get {
                return ResourceManager.GetString("Debug_UnitOfWorkScope_OnCommit", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to UnitOfWorkScope {0} Rolling back..
        /// </summary>
        /// <value>The debug unit of work scope on rollback.</value>
        public static string Debug_UnitOfWorkScope_OnRollback {
            get {
                return ResourceManager.GetString("Debug_UnitOfWorkScope_OnRollback", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Directory does not exist..
        /// </summary>
        /// <value>The exception directory information not exists.</value>
        public static string Exception_DirectoryInfo_Not_Exists {
            get {
                return ResourceManager.GetString("Exception_DirectoryInfo_Not_Exists", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to The scope being committed is not attached to the current transaction..
        /// </summary>
        /// <value>The exception unit of work transaction on scope committing invalid operation exception.</value>
        public static string Exception_UnitOfWorkTransaction_OnScopeCommitting_InvalidOperationException {
            get {
                return ResourceManager.GetString("Exception_UnitOfWorkTransaction_OnScopeCommitting_InvalidOperationException", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Should not throw FormatException due to DateString.
        /// </summary>
        /// <value>The guard geographic location instantiate format exception.</value>
        public static string Guard_GeographicLocation_Instantiate_FormatException {
            get {
                return ResourceManager.GetString("Guard_GeographicLocation_Instantiate_FormatException", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Altitude must be a valid decimal number..
        /// </summary>
        /// <value>The guard geographic location set altitude.</value>
        public static string Guard_GeographicLocation_Set_Altitude {
            get {
                return ResourceManager.GetString("Guard_GeographicLocation_Set_Altitude", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Elevation must be a valid decimal number..
        /// </summary>
        /// <value>The guard geographic location set elevation.</value>
        public static string Guard_GeographicLocation_Set_Elevation {
            get {
                return ResourceManager.GetString("Guard_GeographicLocation_Set_Elevation", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Value was either too large or too small for a Decimal..
        /// </summary>
        /// <value>The guard geographic location set latitude na n.</value>
        public static string Guard_GeographicLocation_Set_Latitude_NaN {
            get {
                return ResourceManager.GetString("Guard_GeographicLocation_Set_Latitude_NaN", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Latitudinal coordinate decimal cannot be greater than 90.
        /// </summary>
        /// <value>The guard geographic location set latitude not greater than 90.</value>
        public static string Guard_GeographicLocation_Set_Latitude_Not_GreaterThan_90 {
            get {
                return ResourceManager.GetString("Guard_GeographicLocation_Set_Latitude_Not_GreaterThan_90", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Latitudinal coordinate decimal cannot be less than 90..
        /// </summary>
        /// <value>The guard geographic location set latitude not less than minus 90.</value>
        public static string Guard_GeographicLocation_Set_Latitude_Not_LessThan_Minus_90 {
            get {
                return ResourceManager.GetString("Guard_GeographicLocation_Set_Latitude_Not_LessThan_Minus_90", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Value was either too large or too small for a Decimal..
        /// </summary>
        /// <value>The guard geographic location set longitude na n.</value>
        public static string Guard_GeographicLocation_Set_Longitude_NaN {
            get {
                return ResourceManager.GetString("Guard_GeographicLocation_Set_Longitude_NaN", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Longitudinal coordinate decimal cannot be greater than 180..
        /// </summary>
        /// <value>The guard geographic location set longitude not greater than 180.</value>
        public static string Guard_GeographicLocation_Set_Longitude_Not_GreaterThan_180 {
            get {
                return ResourceManager.GetString("Guard_GeographicLocation_Set_Longitude_Not_GreaterThan_180", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Longitudinal coordinate decimal cannot be less than 180..
        /// </summary>
        /// <value>The guard geographic location set longitude not less than minus180.</value>
        public static string Guard_GeographicLocation_Set_Longitude_Not_LessThan_Minus180 {
            get {
                return ResourceManager.GetString("Guard_GeographicLocation_Set_Longitude_Not_LessThan_Minus180", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Max Results must be -1 or a positive number..
        /// </summary>
        /// <value>The guard in memory repository constrain query input maximum result equals0.</value>
        public static string Guard_InMemoryRepository_ConstrainQueryInput_MaxResult_Equals0 {
            get {
                return ResourceManager.GetString("Guard_InMemoryRepository_ConstrainQueryInput_MaxResult_Equals0", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Max Results must be -1 or a positive number..
        /// </summary>
        /// <value>The guard in memory repository constrain query input maximum result less than minus1.</value>
        public static string Guard_InMemoryRepository_ConstrainQueryInput_MaxResult_LessThanMinus1 {
            get {
                return ResourceManager.GetString("Guard_InMemoryRepository_ConstrainQueryInput_MaxResult_LessThanMinus1", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Query parameter cannot be null..
        /// </summary>
        /// <value>The guard in memory repository constrain query input query is null.</value>
        public static string Guard_InMemoryRepository_ConstrainQueryInput_Query_IsNull {
            get {
                return ResourceManager.GetString("Guard_InMemoryRepository_ConstrainQueryInput_Query_IsNull", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Start Result must be greater than or equal to zero..
        /// </summary>
        /// <value>The guard in memory repository constrain query input start result less than0.</value>
        public static string Guard_InMemoryRepository_ConstrainQueryInput_StartResult_LessThan0 {
            get {
                return ResourceManager.GetString("Guard_InMemoryRepository_ConstrainQueryInput_StartResult_LessThan0", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to The key must not be null..
        /// </summary>
        /// <value>The guard in memory repository get by key key is null.</value>
        public static string Guard_InMemoryRepository_GetByKey_Key_IsNull {
            get {
                return ResourceManager.GetString("Guard_InMemoryRepository_GetByKey_Key_IsNull", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Input is null.
        /// </summary>
        /// <value>The guard input is null.</value>
        public static string Guard_Input_IsNull {
            get {
                return ResourceManager.GetString("Guard_Input_IsNull", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Token string cannot be empty or null..
        /// </summary>
        /// <value>The guard launch pad token argument exception empty.</value>
        public static string Guard_LaunchPadToken_ArgumentException_Empty {
            get {
                return ResourceManager.GetString("Guard_LaunchPadToken_ArgumentException_Empty", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Token string must contain a name section, beginning with 'n:'..
        /// </summary>
        /// <value>The name of the guard launch pad token argument exception missing.</value>
        public static string Guard_LaunchPadToken_ArgumentException_MissingName {
            get {
                return ResourceManager.GetString("Guard_LaunchPadToken_ArgumentException_MissingName", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Token string must contain a prefix section, beginning with 'p:'..
        /// </summary>
        /// <value>The guard launch pad token argument exception missing prefix.</value>
        public static string Guard_LaunchPadToken_ArgumentException_MissingPrefix {
            get {
                return ResourceManager.GetString("Guard_LaunchPadToken_ArgumentException_MissingPrefix", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Token string must contain at least two sections, delimited by '|'..
        /// </summary>
        /// <value>The guard launch pad token argument exception no delimiter.</value>
        public static string Guard_LaunchPadToken_ArgumentException_NoDelimiter {
            get {
                return ResourceManager.GetString("Guard_LaunchPadToken_ArgumentException_NoDelimiter", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Token string must end with '}}' characters..
        /// </summary>
        /// <value>The guard launch pad token argument exception wrong end with.</value>
        public static string Guard_LaunchPadToken_ArgumentException_WrongEndWith {
            get {
                return ResourceManager.GetString("Guard_LaunchPadToken_ArgumentException_WrongEndWith", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Token string must contain only two (2) to five (5) sections, delimited by '|'..
        /// </summary>
        /// <value>The guard launch pad token argument exception wrong number sections.</value>
        public static string Guard_LaunchPadToken_ArgumentException_WrongNumberSections {
            get {
                return ResourceManager.GetString("Guard_LaunchPadToken_ArgumentException_WrongNumberSections", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Token string must start with '{{' characters..
        /// </summary>
        /// <value>The guard launch pad token argument exception wrong starts with.</value>
        public static string Guard_LaunchPadToken_ArgumentException_WrongStartsWith {
            get {
                return ResourceManager.GetString("Guard_LaunchPadToken_ArgumentException_WrongStartsWith", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Original Text cannot be empty or null..
        /// </summary>
        /// <value>The guard launch pad tokenizer argument exception original text.</value>
        public static string Guard_LaunchPadTokenizer_ArgumentException_OriginalText {
            get {
                return ResourceManager.GetString("Guard_LaunchPadTokenizer_ArgumentException_OriginalText", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to At least one token must be provided..
        /// </summary>
        /// <value>The guard launch pad tokenizer argument exception tokens.</value>
        public static string Guard_LaunchPadTokenizer_ArgumentException_Tokens {
            get {
                return ResourceManager.GetString("Guard_LaunchPadTokenizer_ArgumentException_Tokens", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to No compatible UnitOfWork was found. Please start a compatible UnitOfWorkScope before using the repository..
        /// </summary>
        /// <value>The guard repository base unit of work no compatible type found.</value>
        public static string Guard_RepositoryBase_UnitOfWork_NoCompatibleTypeFound {
            get {
                return ResourceManager.GetString("Guard_RepositoryBase_UnitOfWork_NoCompatibleTypeFound", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to The current UnitOfWork instance is not compatible with the repository. Please start a compatible unit of work before using the repository..
        /// </summary>
        /// <value>The type of the guard repository base unit of work not compatible.</value>
        public static string Guard_RepositoryBase_UnitOfWork_NotCompatibleType {
            get {
                return ResourceManager.GetString("Guard_RepositoryBase_UnitOfWork_NotCompatibleType", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Expected a non null expression as a predicate for the specification..
        /// </summary>
        /// <value>The guard specification specification.</value>
        public static string Guard_Specification_Specification {
            get {
                return ResourceManager.GetString("Guard_Specification_Specification", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to This unit of work scope has been marked completed. A child scope participating in the transaction has rolledback and the transaction aborted. The parent scope cannot be commit..
        /// </summary>
        /// <value>The guard unit of work scope commit invalid operation exception.</value>
        public static string Guard_UnitOfWorkScope_Commit_InvalidOperationException {
            get {
                return ResourceManager.GetString("Guard_UnitOfWorkScope_Commit_InvalidOperationException", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Cannot commit a disposed UnitOfWorkScope instance..
        /// </summary>
        /// <value>The guard unit of work scope commit object disposed exception.</value>
        public static string Guard_UnitOfWorkScope_Commit_ObjectDisposedException {
            get {
                return ResourceManager.GetString("Guard_UnitOfWorkScope_Commit_ObjectDisposedException", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to No compatible UnitOfWork was found. Please start a compatible UnitOfWorkScope before using the repository..
        /// </summary>
        /// <value>The guard unit of work scope current unit of work no compatible type found.</value>
        public static string Guard_UnitOfWorkScope_CurrentUnitOfWork_NoCompatibleTypeFound {
            get {
                return ResourceManager.GetString("Guard_UnitOfWorkScope_CurrentUnitOfWork_NoCompatibleTypeFound", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to The current unit of work is not compatible with expected type {0}, instead the current unit of work is of type {1}..
        /// </summary>
        /// <value>The type of the guard unit of work scope current unit of work not compatible.</value>
        public static string Guard_UnitOfWorkScope_CurrentUnitOfWork_NotCompatibleType {
            get {
                return ResourceManager.GetString("Guard_UnitOfWorkScope_CurrentUnitOfWork_NotCompatibleType", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Expected a non-null IUnitOfWorkScope instance..
        /// </summary>
        /// <value>The guard unit of work transaction enlist scope argument null exception.</value>
        public static string Guard_UnitOfWorkTransaction_EnlistScope_ArgumentNullException {
            get {
                return ResourceManager.GetString("Guard_UnitOfWorkTransaction_EnlistScope_ArgumentNullException", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to The transaction attached to the scope has already been disposed..
        /// </summary>
        /// <value>The guard unit of work transaction on scope committing object disposed exception.</value>
        public static string Guard_UnitOfWorkTransaction_OnScopeCommitting_ObjectDisposedException {
            get {
                return ResourceManager.GetString("Guard_UnitOfWorkTransaction_OnScopeCommitting_ObjectDisposedException", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to The transaction attached to the scope has already been disposed..
        /// </summary>
        /// <value>The guard unit of work transaction on scope rolling back object disposed exception.</value>
        public static string Guard_UnitOfWorkTransaction_OnScopeRollingBack_ObjectDisposedException {
            get {
                return ResourceManager.GetString("Guard_UnitOfWorkTransaction_OnScopeRollingBack_ObjectDisposedException", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Expected a non-null TransactionScope instance..
        /// </summary>
        /// <value>The guard unit of work transaction unit of work transaction argument null exception transaction.</value>
        public static string Guard_UnitOfWorkTransaction_UnitOfWorkTransaction_ArgumentNullException_transaction {
            get {
                return ResourceManager.GetString("Guard_UnitOfWorkTransaction_UnitOfWorkTransaction_ArgumentNullException_transacti" +
                        "on", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Expected a non-null UnitOfWork instance..
        /// </summary>
        /// <value>The guard unit of work transaction unit of work transaction argument null exception unit of work.</value>
        public static string Guard_UnitOfWorkTransaction_UnitOfWorkTransaction_ArgumentNullException_unitOfWork {
            get {
                return ResourceManager.GetString("Guard_UnitOfWorkTransaction_UnitOfWorkTransaction_ArgumentNullException_unitOfWor" +
                        "k", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Attribute name cannot be null or empty..
        /// </summary>
        /// <value>The guard XHTML helper attribute name is null.</value>
        public static string Guard_XhtmlHelper_AttributeName_Is_Null {
            get {
                return ResourceManager.GetString("Guard_XhtmlHelper_AttributeName_Is_Null", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to ParentNode cannot be null..
        /// </summary>
        /// <value>The guard XHTML helper parent node is null.</value>
        public static string Guard_XhtmlHelper_ParentNode_Is_Null {
            get {
                return ResourceManager.GetString("Guard_XhtmlHelper_ParentNode_Is_Null", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to PropertySetsNodes collection is null or empty..
        /// </summary>
        /// <value>The guard XHTML helper property sets nodes is null.</value>
        public static string Guard_XhtmlHelper_PropertySetsNodes_Is_Null {
            get {
                return ResourceManager.GetString("Guard_XhtmlHelper_PropertySetsNodes_Is_Null", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to XPath cannot be null or empty..
        /// </summary>
        /// <value>The guard XHTML helper x path is null.</value>
        public static string Guard_XhtmlHelper_XPath_Is_Null {
            get {
                return ResourceManager.GetString("Guard_XhtmlHelper_XPath_Is_Null", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Disposing of transaction manager {0}..
        /// </summary>
        /// <value>The information transaction manager dispose.</value>
        public static string Info_TransactionManager_Dispose {
            get {
                return ResourceManager.GetString("Info_TransactionManager_Dispose", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Enlisting scope {0} with transaction manager {1} with transaction mode {2}..
        /// </summary>
        /// <value>The information transaction manager enlist scope enlisting scope.</value>
        public static string Info_TransactionManager_EnlistScope_EnlistingScope {
            get {
                return ResourceManager.GetString("Info_TransactionManager_EnlistScope_EnlistingScope", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Enlisting scope {0} with mode {1} requires a new TransactionScope to be created..
        /// </summary>
        /// <value>The information transaction manager enlist scope enlisting scope requires new transaction scope.</value>
        public static string Info_TransactionManager_EnlistScope_EnlistingScopeRequiresNewTransactionScope {
            get {
                return ResourceManager.GetString("Info_TransactionManager_EnlistScope_EnlistingScopeRequiresNewTransactionScope", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to UnitOfWorkTransaction {0} signalled a disposed. Unregistering transaction from TransactionManager {1}..
        /// </summary>
        /// <value>The information transaction manager on transaction disposing.</value>
        public static string Info_TransactionManager_OnTransactionDisposing {
            get {
                return ResourceManager.GetString("Info_TransactionManager_OnTransactionDisposing", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Disposing off transction {0}..
        /// </summary>
        /// <value>The information unit of work transaction dispose disposing.</value>
        public static string Info_UnitOfWorkTransaction_Dispose_Disposing {
            get {
                return ResourceManager.GetString("Info_UnitOfWorkTransaction_Dispose_Disposing", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Scope {0} enlisted with transaction {1}..
        /// </summary>
        /// <value>The information unit of work transaction enlist scope enlisted.</value>
        public static string Info_UnitOfWorkTransaction_EnlistScope_Enlisted {
            get {
                return ResourceManager.GetString("Info_UnitOfWorkTransaction_EnlistScope_Enlisted", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to All scopes have signalled a commit on transaction {0}. Flushing unit of work and commiting attached TransactionScope..
        /// </summary>
        /// <value>The information unit of work transaction on scope committing committing.</value>
        public static string Info_UnitOfWorkTransaction_OnScopeCommitting_Committing {
            get {
                return ResourceManager.GetString("Info_UnitOfWorkTransaction_OnScopeCommitting_Committing", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Commit signalled by scope {0} on transaction {1}..
        /// </summary>
        /// <value>The information unit of work transaction on scope committing signalled.</value>
        public static string Info_UnitOfWorkTransaction_OnScopeCommitting_Signalled {
            get {
                return ResourceManager.GetString("Info_UnitOfWorkTransaction_OnScopeCommitting_Signalled", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Detaching all scopes and disposing of attached TransactionScope on transaction {0}..
        /// </summary>
        /// <value>The information unit of work transaction on scope rolling back disposing.</value>
        public static string Info_UnitOfWorkTransaction_OnScopeRollingBack_Disposing {
            get {
                return ResourceManager.GetString("Info_UnitOfWorkTransaction_OnScopeRollingBack_Disposing", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Rollback signalled by scope {0} on transaction {1}..
        /// </summary>
        /// <value>The information unit of work transaction on scope rolling back signalled.</value>
        public static string Info_UnitOfWorkTransaction_OnScopeRollingBack_Signalled {
            get {
                return ResourceManager.GetString("Info_UnitOfWorkTransaction_OnScopeRollingBack_Signalled", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to New UnitOfWorkTransction created with Id {0}..
        /// </summary>
        /// <value>The information unit of work transaction unit of work transaction created.</value>
        public static string Info_UnitOfWorkTransaction_UnitOfWorkTransaction_Created {
            get {
                return ResourceManager.GetString("Info_UnitOfWorkTransaction_UnitOfWorkTransaction_Created", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Item "{0}" was added to the collection..
        /// </summary>
        /// <value>The logger information item added.</value>
        public static string Logger_Info_ItemAdded {
            get {
                return ResourceManager.GetString("Logger_Info_ItemAdded", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Item "{0}" already exists in the collection..
        /// </summary>
        /// <value>The logger information item already exists.</value>
        public static string Logger_Info_ItemAlreadyExists {
            get {
                return ResourceManager.GetString("Logger_Info_ItemAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Item "{0}" already existed in the collection, overwrote it with new value..
        /// </summary>
        /// <value>The logger information item already exists overwriting.</value>
        public static string Logger_Info_ItemAlreadyExistsOverwriting {
            get {
                return ResourceManager.GetString("Logger_Info_ItemAlreadyExistsOverwriting", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Open Government is about making government more accessible to everyone.
        /// This means giving greater access to government data and information to the Canadian public and the businesses community.
        /// The Information Provider grants you a worldwide, royalty-free, perpetual, non-exclusive licence to use the Information,
        /// including for commercial purposes, subject to the license terms.
        /// [rest of string was truncated]";.
        /// </summary>
        /// <value>The text open government canada license license description.</value>
        public static string Text_OpenGovernmentCanadaLicense_LicenseDescription {
            get {
                return ResourceManager.GetString("Text_OpenGovernmentCanadaLicense_LicenseDescription", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Open Government License - Canada.
        /// </summary>
        /// <value>The name of the text open government canada license license.</value>
        public static string Text_OpenGovernmentCanadaLicense_LicenseName {
            get {
                return ResourceManager.GetString("Text_OpenGovernmentCanadaLicense_LicenseName", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to https://open.canada.ca/en/open-government-licence-canada.
        /// </summary>
        /// <value>The text open government canada license license terms.</value>
        public static string Text_OpenGovernmentCanadaLicense_LicenseTerms {
            get {
                return ResourceManager.GetString("Text_OpenGovernmentCanadaLicense_LicenseTerms", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Correlation ID field must be 36 characters or less..
        /// </summary>
        /// <value>The validation correlation identifier 36 chars or less.</value>
        public static string Validation_CorrelationId_36CharsOrLess {
            get {
                return ResourceManager.GetString("Validation_CorrelationId_36CharsOrLess", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Culture must be 5 characters or less..
        /// </summary>
        /// <value>The validation culture 5 chars or less.</value>
        public static string Validation_Culture_5CharsOrLess {
            get {
                return ResourceManager.GetString("Validation_Culture_5CharsOrLess", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Description Full must be 8096 characters or less..
        /// </summary>
        /// <value>The validation description full 8096 chars or less.</value>
        public static string Validation_DescriptionFull_8096CharsOrLess {
            get {
                return ResourceManager.GetString("Validation_DescriptionFull_8096CharsOrLess", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Description Short must be 256 characters or less..
        /// </summary>
        /// <value>The validation description short 256 chars or less.</value>
        public static string Validation_DescriptionShort_256CharsOrLess {
            get {
                return ResourceManager.GetString("Validation_DescriptionShort_256CharsOrLess", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to External ID field must be 36 characters or less..
        /// </summary>
        /// <value>The validation external identifier 36 chars or less.</value>
        public static string Validation_ExternalId_36CharsOrLess {
            get {
                return ResourceManager.GetString("Validation_ExternalId_36CharsOrLess", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Name must be 100 characters or less..
        /// </summary>
        /// <value>The validation name 100 chars or less.</value>
        public static string Validation_Name_100CharsOrLess {
            get {
                return ResourceManager.GetString("Validation_Name_100CharsOrLess", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Name must be 256 characters or less..
        /// </summary>
        /// <value>The validation name 256 chars or less.</value>
        public static string Validation_Name_256CharsOrLess {
            get {
                return ResourceManager.GetString("Validation_Name_256CharsOrLess", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Token name must be 20 characters or less..
        /// </summary>
        /// <value>The validation token name 20 chars or less.</value>
        public static string Validation_Token_Name_20CharsOrLess {
            get {
                return ResourceManager.GetString("Validation_Token_Name_20CharsOrLess", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Token prefix must be 9 characters or less..
        /// </summary>
        /// <value>The validation token prefix 9 chars or less.</value>
        public static string Validation_Token_Prefix_9CharsOrLess {
            get {
                return ResourceManager.GetString("Validation_Token_Prefix_9CharsOrLess", resourceCulture);
            }
        }
    }
}
