using System;
using System.Collections.Generic;
using System.Text;

namespace DeploySoftware.LaunchPad.Core.CodeGeneration
{
    /// <summary>
    /// Represents a C# DTO generated by LaunchPad Framework.
    /// </summary>
    public partial class LaunchPadGeneratedDataTransferObject : LaunchPadGeneratedClass
    {



    }
}
