using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.CodeGeneration
{
    /// <summary>
    /// Represents a module generated by LaunchPad Framework.
    /// </summary>
    public partial class LaunchPadGeneratedModule : LaunchPadGeneratedObjectBase
    {
        /// <summary>
        /// Contains information related to this object's position with a Visual Studio solution
        /// </summary>
        public LaunchPadGeneratedVisualStudioSolutionConfiguration VisualStudioConfig { get; set; }

        /// <summary>
        /// The version of this module
        /// </summary>
        public string Version { get; set; }

        /// <summary>
        /// The id type of the entities (if any).
        /// </summary>
        public string EntityIdType { get; set; }

        /// <summary>
        /// The list of components that belong to this module.
        /// </summary>
        public IList<LaunchPadGeneratedComponent> Components { get; set; }

        public LaunchPadGeneratedModule() : base()
        {
            Version = string.Empty;
            EntityIdType = string.Empty;
            Components = new List<LaunchPadGeneratedComponent>();
            VisualStudioConfig = new LaunchPadGeneratedVisualStudioSolutionConfiguration();
        }
    }
}
