using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a solution generated by LaunchPad Framework which only contains static web resources.
    /// </summary>
    [Serializable]
    public partial class LaunchPadGeneratedStaticWebSolution : LaunchPadGeneratedSolutionBase
    {

        /// <summary>
        /// The list of generated static web resource modules that belong to this solution.
        /// </summary>
        public IList<LaunchPadGeneratedStaticWebModule> StaticWebModules { get; set; }

        public LaunchPadGeneratedStaticWebSolution() : base()
        {
            Version = string.Empty;
            StaticWebModules = new List<LaunchPadGeneratedStaticWebModule>();
        }
    }
}
