using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a set of related static web pages or resources (.htm or CSS etc) generated by LaunchPad Framework.
    /// </summary>
    public partial class LaunchPadGeneratedStaticWebModule : LaunchPadGeneratedModuleBase
    {
        /// <summary>
        /// The list of static web pages that belong to this module.
        /// </summary>
        public IList<LaunchPadGeneratedStaticWebPage> StaticWebPages { get; set; }

        /// <summary>
        /// The list of static stylesheets (.css) that belong to this module.
        /// </summary>
        public IList<LaunchPadGeneratedStaticStylesheet> StaticStylesheets { get; set; }

        public LaunchPadGeneratedStaticWebModule() : base()
        {
            StaticWebPages = new List<LaunchPadGeneratedStaticWebPage>();
            StaticStylesheets = new List<LaunchPadGeneratedStaticStylesheet>();
        }

    }
}
