using System;
using System.Collections.Generic;
using System.Xml.Serialization;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a set of related dynamic angular web pages as well as related resources (.htm or CSS etc) 
    /// generated by LaunchPad Framework.
    /// </summary>
    [Serializable]
    public partial class LaunchPadGeneratedWebClientModule : 
        LaunchPadGeneratedModule<LaunchPadGeneratedWebClientModuleConfiguration, 
            LaunchPadGeneratedComponent<LaunchPadGeneratedConfiguration>,
            LaunchPadGeneratedConfiguration>
    {
        /// <summary>
        /// Brand configuration of the app. Thsi could include name, icon, logo and/or theme color.
        /// </summary>
        [XmlElement]
        public LaunchPadBrand Brand { get; set; }

        /// <summary>
        /// The top section of the side navigation bar
        /// </summary>
        [XmlElement]
        public IDictionary<string, LaunchPadNavigationItem> TopNavigations { get; set; }

        /// <summary>
        /// The bottom section of the side navigation bar
        /// </summary>
        [XmlElement]
        public IDictionary<string, LaunchPadNavigationItem> BottomNavigations { get; set; }

        /// <summary>
        /// The list of static web pages that belong to this module.
        /// </summary>
        [XmlElement]
        public virtual IDictionary<string, LaunchPadGeneratedStaticWebPage> StaticWebPages { get; set; }

        /// <summary>
        /// The dictionary of dynamic stylesheets (.less or .sass) that belong to this module.
        /// </summary>
        [XmlElement]
        public virtual IDictionary<string, LaunchPadGeneratedStylesheet> Stylesheets { get; set; }

        public LaunchPadGeneratedWebClientModule() : base()
        {
            Brand = new LaunchPadBrand();
            var comparer = StringComparer.OrdinalIgnoreCase;
            TopNavigations = new Dictionary<string, LaunchPadNavigationItem>(comparer);
            BottomNavigations = new Dictionary<string, LaunchPadNavigationItem>(comparer);
        }

    }
}
