using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a set of related dynamic angular web pages as well as related resources (.htm or CSS etc) 
    /// generated by LaunchPad Framework.
    /// </summary>
    [Serializable]
    public partial class LaunchPadGeneratedWebClientModule : 
        LaunchPadGeneratedModule<LaunchPadGeneratedWebClientModuleConfiguration, 
            LaunchPadGeneratedComponent<LaunchPadGeneratedConfiguration>,
            LaunchPadGeneratedConfiguration>
    {
        /// <summary>
        /// The list of angular modules that belong to this module.
        /// </summary>
        public virtual IDictionary<string, LaunchPadGeneratedAngularModule> AngularModules { get; set; }

        /// <summary>
        /// The list of static web pages that belong to this module.
        /// </summary>
        public virtual IDictionary<string, LaunchPadGeneratedStaticWebPage> StaticWebPages { get; set; }

        /// <summary>
        /// The dictionary of dynamic stylesheets (.less or .sass) that belong to this module.
        /// </summary>
        public virtual IDictionary<string, LaunchPadGeneratedStylesheet> Stylesheets { get; set; }

        public LaunchPadGeneratedWebClientModule() : base()
        {
            var comparer = StringComparer.OrdinalIgnoreCase;
            AngularModules = new Dictionary<string, LaunchPadGeneratedAngularModule>(comparer);
            StaticWebPages = new Dictionary<string, LaunchPadGeneratedStaticWebPage>(comparer);
            Stylesheets = new Dictionary<string, LaunchPadGeneratedStylesheet>(comparer);
        }

    }
}
