using System;
using System.Collections.Generic;
using System.Text;

namespace DeploySoftware.LaunchPad.Core.Domain.Entities.SoftwareApplications
{
    /// <summary>
    /// Represents a C# property generated by LaunchPad Framework.
    /// </summary>
    public class LaunchPadGeneratedProperty : LaunchPadGeneratedObjectBase
    {

        public string DataType { get; set; } = "System.String";

        public string DefaultValue { get; set; }

        public bool IsOptional { get; set; }

        public bool IsReadonly { get; set; }
        

    }
}
