using System;
using System.Collections.Generic;
using System.Text;

namespace DeploySoftware.LaunchPad.Core.Domain.Entities.SoftwareApplications
{ 
    /// <summary>
  /// Represents a C# DTO generated by LaunchPad Framework.
  /// </summary>
    public class LaunchPadGeneratedDataTransferObject
    {
        public string Name { get; set; }

        public string Prefix { get; set; }

        public string Suffix { get; set; }

        public string Namespace { get; set; }

        public string Project { get; set; }

        public string SubFolder { get; set; }

        public string InheritsFrom { get; set; }
    }
}
