using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.Domain.Entities.SoftwareApplications
{
    /// <summary>
    /// Represents a C# class method generated by LaunchPad Framework.
    /// </summary>
    public class LaunchPadGeneratedMethod : LaunchPadGeneratedObjectBase
    {

        public SortedDictionary<string, LaunchPadGeneratedMethodParameter> Parameters;
        
        public string Returns { get; set; }
    }

    public class LaunchPadGeneratedMethodParameter
    {
        public string Name { get; set; }
        public string DataType { get; set; } = "System.String";
        public string DefaultValue { get; set; }
    }
}
