using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.Domain.Entities.SoftwareApplications
{
    /// <summary>
    /// Represents a C# class generated by LaunchPad Framework.
    /// </summary>
    public class LaunchPadGeneratedClass
    {
        public string Project { get; set; }
        public string SubFolder { get; set; }
        public string Name { get; set; }
        public string InheritsFrom { get; set; }
        public string Namespace { get; set; }
        public string PrimaryKeyType { get; set; }

        public string Description { get; set; }

        public string Annotations { get; set; }
        
        public IList<LaunchPadGeneratedProperty> GeneratedProperties { get; set; }
        public IList<LaunchPadGeneratedMethod> GeneratedMethods { get; set; }

        public LaunchPadGeneratedClass()
        {
            GeneratedProperties = new List<LaunchPadGeneratedProperty>();
            GeneratedMethods = new List<LaunchPadGeneratedMethod>();
        }
    }
}
