// ***********************************************************************
// Assembly         : Deploy.LaunchPad.FileGeneration
// Author           : Nicholas Kellett
// Created          : 11-19-2023
//
// Last Modified By : Nicholas Kellett
// Last Modified On : 11-04-2023
// ***********************************************************************
// <copyright file="AbpModuleDefinition.cs" company="Deploy Software Solutions, inc.">
//     2018-2023 Deploy Software Solutions, inc.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;

namespace Deploy.LaunchPad.FileGeneration.Structure.AbpModules
{
    /// <summary>
    /// Represents an AspNetBoilerplate "module" that is generated by LaunchPad Framework and provides functionality in the .NET application.
    /// Although the name sounds similar to LaunchPad framework's "modules", the concept is more like our "Components" since it contains very low-level, composable functionality.
    /// see https://aspnetboilerplate.com/Pages/Documents/Module-System
    /// </summary>
    [Serializable]
    public partial class AbpModuleDefinition : LaunchPadGeneratedClassBase
    {

        /// <summary>
        /// Gets or sets the path.
        /// </summary>
        /// <value>The path.</value>
        public virtual string Path { get; set; }

        /// <summary>
        /// Gets or sets the dependencies.
        /// </summary>
        /// <value>The dependencies.</value>
        public virtual ModuleDependencyInformation Dependencies { get; set; }


        /// <summary>
        /// Initializes a new instance of the <see cref="AbpModuleDefinition"/> class.
        /// </summary>
        public AbpModuleDefinition()
        {
            Name = string.Empty;
            Path = string.Empty;
            Dependencies = new ModuleDependencyInformation();
        }

    }
}
