using System;
using System.Collections.Generic;

namespace Deploy.LaunchPad.FileGeneration.Structure.AbpModules
{
    /// <summary>
    /// Represents an AspNetBoilerplate "module" that is generated by LaunchPad Framework and provides functionality in the .NET application.
    /// Although the name sounds similar to LaunchPad framework's "modules", the concept is more like our "Components" since it contains very low-level, composable functionality.
    /// see https://aspnetboilerplate.com/Pages/Documents/Module-System
    /// </summary>    
    [Serializable]
    public partial class AbpModuleDefinition : LaunchPadGeneratedClassBase
    {

        public virtual string Path { get; set; }

        public virtual ModuleDependencyInformation Dependencies { get; set; }


        public AbpModuleDefinition()
        {
            Name = string.Empty;
            Path = string.Empty;
            Dependencies = new ModuleDependencyInformation();
        }

    }
}
