using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents a static web page  (.htm, .html etc) generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedStaticWebPage : LaunchPadGeneratedObjectBase
    {


        public LaunchPadGeneratedStaticWebPage() : base()
        {
           
        }
    }
}
