using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents a static css file generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedStylesheet : LaunchPadGeneratedObjectBase
    {

        public LaunchPadGeneratedStylesheet() : base()
        {
           
        }
    }
}
