using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents a Value Object class generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedValueObject : LaunchPadGeneratedClassBase
    {

        public LaunchPadGeneratedValueObject() : base()
        {
        }
    }
}
