// ***********************************************************************
// Assembly         : Deploy.LaunchPad.FileGeneration
// Author           : Nicholas Kellett
// Created          : 11-19-2023
//
// Last Modified By : Nicholas Kellett
// Last Modified On : 01-08-2023
// ***********************************************************************
// <copyright file="DocumentSetComponent.cs" company="Deploy Software Solutions, inc.">
//     2018-2023 Deploy Software Solutions, inc.
// </copyright>
// <summary></summary>
// ***********************************************************************
using Castle.Core.Logging;
using System;
using System.Collections.Generic;

namespace Deploy.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents a document set component generated by LaunchPad Framework.
    /// </summary>
    [Serializable]
    public partial class DocumentSetComponent
        : LaunchPadGeneratedComponent<DocumentSetBlueprintDefinitionSettings, DocumentSetBlueprintDefinitionInstructions>
    {

        /// <summary>
        /// The list of folders that belong to this module.
        /// </summary>
        /// <value>The folders.</value>
        public virtual IDictionary<string, LaunchPadGeneratedFolder> Folders { get; set; }

        /// <summary>
        /// The list of documents that belong to this module.
        /// </summary>
        /// <value>The documents.</value>
        public virtual IDictionary<string, LaunchPadGeneratedDocument> Documents { get; set; }

        /// <summary>
        /// Returns a bool indicating if the document set component is currently in a valid or invalid state.
        /// </summary>
        /// <returns>True if the document set component is in a valid state, or false if it is contains missing or invalid elements.</returns>
        public override bool CheckValidity()
        {
            bool isValid = false;
            if (BlueprintDefinition != null
                && ((Folders != null && Folders.Count > 0) || (Documents != null && Documents.Count > 0))
                && (Documents.Count > 0 || Folders.Count > 0)
            )
            {
                isValid = true;
            }
            return isValid;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentSetComponent"/> class.
        /// </summary>
        public DocumentSetComponent() : base(NullLogger.Instance)
        {
            var comparer = StringComparer.OrdinalIgnoreCase;
            Folders = new Dictionary<string, LaunchPadGeneratedFolder>(comparer);
            Documents = new Dictionary<string, LaunchPadGeneratedDocument>(comparer);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentSetComponent"/> class.
        /// </summary>
        /// <param name="logger">The logger.</param>
        public DocumentSetComponent(ILogger logger) : base(logger)
        {
            var comparer = StringComparer.OrdinalIgnoreCase;
            Folders = new Dictionary<string, LaunchPadGeneratedFolder>(comparer);
            Documents = new Dictionary<string, LaunchPadGeneratedDocument>(comparer);
        }
    }
}
