// ***********************************************************************
// Assembly         : Deploy.LaunchPad.FileGeneration
// Author           : Nicholas Kellett
// Created          : 11-19-2023
//
// Last Modified By : Nicholas Kellett
// Last Modified On : 01-08-2023
// ***********************************************************************
// <copyright file="LaunchPadGeneratedDocument.cs" company="Deploy Software Solutions, inc.">
//     2018-2023 Deploy Software Solutions, inc.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;

namespace Deploy.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents an office document (Word, Excel, Powerpoint, RTF) generated by LaunchPad Framework.
    /// </summary>
    [Serializable]
    public partial class LaunchPadGeneratedDocument : LaunchPadGeneratedObjectBase
    {
        /// <summary>
        /// Gets or sets the type of the MIME.
        /// </summary>
        /// <value>The type of the MIME.</value>
        public virtual string MimeType { get; set; }

        /// <summary>
        /// Gets or sets the extension.
        /// </summary>
        /// <value>The extension.</value>
        public virtual string Extension { get; set; }

        /// <summary>
        /// Gets or sets the name of the folder.
        /// </summary>
        /// <value>The name of the folder.</value>
        public virtual string FolderName { get; set; }

        /// <summary>
        /// Gets or sets the file path.
        /// </summary>
        /// <value>The file path.</value>
        public virtual string FilePath { get; set; }

        /// <summary>
        /// Contains information on the template(s) that should be used to generate this document (if any).
        /// If none are listed, templates may be applied if listed in the parent Document Set Module (again, if listed).
        /// </summary>
        /// <value>The templates.</value>
        public virtual LaunchPadGeneratedDocumentTemplates Templates { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="LaunchPadGeneratedDocument"/> class.
        /// </summary>
        public LaunchPadGeneratedDocument() : base()
        {
            MimeType = string.Empty;
            Extension = string.Empty;
            FolderName = string.Empty;
            FilePath = string.Empty;
            Templates = new LaunchPadGeneratedDocumentTemplates();
        }
    }
}
