// ***********************************************************************
// Assembly         : Deploy.LaunchPad.Images
// Author           : Nicholas Kellett
// Created          : 11-19-2023
//
// Last Modified By : Nicholas Kellett
// Last Modified On : 01-08-2023
// ***********************************************************************
// <copyright file="Deploy.LaunchPad.Images.Resources.Designer.cs" company="Deploy Software Solutions, inc.">
//     2016-2023 Deploy Software Solutions, inc.
// </copyright>
// <summary></summary>
// ***********************************************************************

namespace Deploy.LaunchPad.Images {
    using System;


    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Deploy_LaunchPad_Images_Resources {

        /// <summary>
        /// The resource man
        /// </summary>
        private static global::System.Resources.ResourceManager resourceMan;

        /// <summary>
        /// The resource culture
        /// </summary>
        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Initializes a new instance of the <see cref="Deploy_LaunchPad_Images_Resources"/> class.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Deploy_LaunchPad_Images_Resources() {
        }

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        /// <value>The resource manager.</value>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Deploy.LaunchPad.Images.Deploy.LaunchPad.Images.Resources", typeof(Deploy_LaunchPad_Images_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        /// <value>The culture.</value>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to ImageMagick does not know how to compare these formats. More information may be found by searching online for MagickMissingDelegateErrorException 'no encode delegate for this image format'.
        /// </summary>
        /// <value>The exception image manager compare images magick missing delegate error exception.</value>
        public static string Exception_ImageManager_CompareImages_MagickMissingDelegateErrorException {
            get {
                return ResourceManager.GetString("Exception_ImageManager_CompareImages_MagickMissingDelegateErrorException", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to ImageMagick threw an error when attempting to create a new MagickImage from the provide information.
        /// </summary>
        /// <value>The exception image manager get magick image from file invalid operation exception.</value>
        public static string Exception_ImageManager_GetMagickImageFromFile_InvalidOperationException {
            get {
                return ResourceManager.GetString("Exception_ImageManager_GetMagickImageFromFile_InvalidOperationException", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Height must be greater than 0.
        /// </summary>
        /// <value>The guard image manager thumbnail height argument out of range exception.</value>
        public static string Guard_ImageManager_Thumbnail_Height_ArgumentOutOfRangeException {
            get {
                return ResourceManager.GetString("Guard_ImageManager_Thumbnail_Height_ArgumentOutOfRangeException", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Image A is empty - byte size must be greater than 0.
        /// </summary>
        /// <value>The guard image manager thumbnail image a argument out of range exception.</value>
        public static string Guard_ImageManager_Thumbnail_ImageA_ArgumentOutOfRangeException {
            get {
                return ResourceManager.GetString("Guard_ImageManager_Thumbnail_ImageA_ArgumentOutOfRangeException", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Image A is null.
        /// </summary>
        /// <value>The guard image manager thumbnail image a null reference exception.</value>
        public static string Guard_ImageManager_Thumbnail_ImageA_NullReferenceException {
            get {
                return ResourceManager.GetString("Guard_ImageManager_Thumbnail_ImageA_NullReferenceException", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Image B is empty - byte size must be greater than 0.
        /// </summary>
        /// <value>The guard image manager thumbnail image b argument out of range exception.</value>
        public static string Guard_ImageManager_Thumbnail_ImageB_ArgumentOutOfRangeException {
            get {
                return ResourceManager.GetString("Guard_ImageManager_Thumbnail_ImageB_ArgumentOutOfRangeException", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Image B is null.
        /// </summary>
        /// <value>The guard image manager thumbnail image b null reference exception.</value>
        public static string Guard_ImageManager_Thumbnail_ImageB_NullReferenceException {
            get {
                return ResourceManager.GetString("Guard_ImageManager_Thumbnail_ImageB_NullReferenceException", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Original image is null.
        /// </summary>
        /// <value>The guard image manager thumbnail original image argument null exception.</value>
        public static string Guard_ImageManager_Thumbnail_OriginalImage_ArgumentNullException {
            get {
                return ResourceManager.GetString("Guard_ImageManager_Thumbnail_OriginalImage_ArgumentNullException", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Original image is empty - byte size must be greater than 0.
        /// </summary>
        /// <value>The guard image manager thumbnail original image argument out of range exception.</value>
        public static string Guard_ImageManager_Thumbnail_OriginalImage_ArgumentOutOfRangeException {
            get {
                return ResourceManager.GetString("Guard_ImageManager_Thumbnail_OriginalImage_ArgumentOutOfRangeException", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Width must be greater than 0.
        /// </summary>
        /// <value>The guard image manager thumbnail width argument out of range exception.</value>
        public static string Guard_ImageManager_Thumbnail_Width_ArgumentOutOfRangeException {
            get {
                return ResourceManager.GetString("Guard_ImageManager_Thumbnail_Width_ArgumentOutOfRangeException", resourceCulture);
            }
        }
    }
}
