//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploySoftware.LaunchPad.Core.Abp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DeploySoftware_LaunchPad_Core_Abp_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeploySoftware_LaunchPad_Core_Abp_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeploySoftware.LaunchPad.Core.Abp.DeploySoftware.LaunchPad.Core.Abp.Resources", typeof(DeploySoftware_LaunchPad_Core_Abp_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed background job: &apos;{0}&apos;.
        /// </summary>
        public static string Logger_Debug_BackgroundJob_Executed {
            get {
                return ResourceManager.GetString("Logger_Debug_BackgroundJob_Executed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing background job: &apos;{0}&apos;.
        /// </summary>
        public static string Logger_Debug_BackgroundJob_Executing {
            get {
                return ResourceManager.GetString("Logger_Debug_BackgroundJob_Executing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started background worker: &apos;{0}&apos;.
        /// </summary>
        public static string Logger_Debug_BackgroundWorker_Started {
            get {
                return ResourceManager.GetString("Logger_Debug_BackgroundWorker_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting background worker: &apos;{0}&apos;.
        /// </summary>
        public static string Logger_Debug_BackgroundWorker_Starting {
            get {
                return ResourceManager.GetString("Logger_Debug_BackgroundWorker_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped background worker: &apos;{0}&apos;.
        /// </summary>
        public static string Logger_Debug_BackgroundWorker_Stopped {
            get {
                return ResourceManager.GetString("Logger_Debug_BackgroundWorker_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping background worker: &apos;{0}&apos;.
        /// </summary>
        public static string Logger_Debug_BackgroundWorker_Stopping {
            get {
                return ResourceManager.GetString("Logger_Debug_BackgroundWorker_Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished waiting to stop background worker: &apos;{0}&apos;.
        /// </summary>
        public static string Logger_Debug_BackgroundWorker_WaitedToStop {
            get {
                return ResourceManager.GetString("Logger_Debug_BackgroundWorker_WaitedToStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to stop background worker: &apos;{0}&apos;.
        /// </summary>
        public static string Logger_Debug_BackgroundWorker_WaitingToStop {
            get {
                return ResourceManager.GetString("Logger_Debug_BackgroundWorker_WaitingToStop", resourceCulture);
            }
        }
    }
}
