using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a solution generated by LaunchPad Framework which may include code, documents, and static html.
    /// </summary>
    [Serializable]
    public partial class LaunchPadGeneratedVisualStudioSolution : LaunchPadGeneratedSolution
    {

        /// <summary>
        /// The list of generated Visual Studio modules that belong to this solution.
        /// </summary>
        public virtual IDictionary<string, LaunchPadGeneratedVisualStudioModule> VisualStudioModules { get; set; }

        /// <summary>
        /// The list of generated document set modules that belong to this solution.
        /// </summary>
        public virtual IDictionary<string, LaunchPadGeneratedDocumentSetModule> DocumentSetModules { get; set; }

        /// <summary>
        /// The set of generated static web resource modules that belong to this solution.
        /// </summary>
        public virtual IDictionary<string, LaunchPadGeneratedStaticWebModule> StaticWebModules { get; set; }


        public LaunchPadGeneratedVisualStudioSolution() : base()
        {
            var comparer = StringComparer.OrdinalIgnoreCase;
            VisualStudioModules = new Dictionary<string,LaunchPadGeneratedVisualStudioModule>(comparer);
            DocumentSetModules = new Dictionary<string, LaunchPadGeneratedDocumentSetModule>(comparer);
            StaticWebModules = new Dictionary<string, LaunchPadGeneratedStaticWebModule>(comparer);
        }
    }
}
