using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a module generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedVisualStudioModule : 
        LaunchPadGeneratedModule<LaunchPadGeneratedVisualStudioModuleConfiguration,
            LaunchPadGeneratedVisualStudioComponent,
            LaunchPadGeneratedVisualStudioComponentConfiguration>
    {

        /// <summary>
        /// The id type of the entities (if any).
        /// </summary>
        public virtual string EntityIdType { get; set; }


        public LaunchPadGeneratedVisualStudioModule() : base()
        {
            EntityIdType = string.Empty;
        }
    }
}
