// ***********************************************************************
// Assembly         : Deploy.LaunchPad.FileGeneration
// Author           : Nicholas Kellett
// Created          : 11-19-2023
//
// Last Modified By : Nicholas Kellett
// Last Modified On : 01-08-2023
// ***********************************************************************
// <copyright file="UnspecifiedComponent.cs" company="Deploy Software Solutions, inc.">
//     2018-2023 Deploy Software Solutions, inc.
// </copyright>
// <summary></summary>
// ***********************************************************************
using Castle.Core.Logging;
using System;

namespace Deploy.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents a generic component generated by LaunchPad Framework.
    /// </summary>
    [Serializable]
    public partial class UnspecifiedComponent
        : LaunchPadGeneratedComponent<UnspecifiedBlueprintDefinitionSettings, UnspecifiedBlueprintDefinitionInstructions>
    {

        /// <summary>
        /// Returns a bool indicating if the component is currently in a valid or invalid state.
        /// </summary>
        /// <returns>True if the component is in a valid state, or false if it is contains missing or invalid elements.</returns>
        public override bool CheckValidity()
        {
            bool isValid = false;
            if (BlueprintDefinition != null
            )
            {
                isValid = true;
            }
            return isValid;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UnspecifiedComponent"/> class.
        /// </summary>
        public UnspecifiedComponent() : base(NullLogger.Instance)
        {

        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UnspecifiedComponent"/> class.
        /// </summary>
        /// <param name="logger">The logger.</param>
        public UnspecifiedComponent(ILogger logger) : base(logger)
        {
        }

    }
}
