using Castle.Core.Logging;
using System;

namespace Deploy.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents a generic component generated by LaunchPad Framework.
    /// </summary>
    [Serializable]
    public partial class UnspecifiedComponent
        : LaunchPadGeneratedComponent<UnspecifiedBlueprintDefinitionSettings, UnspecifiedBlueprintDefinitionInstructions>
    {

        /// <summary>
        /// Returns a bool indicating if the component is currently in a valid or invalid state.
        /// </summary>
        /// <returns>True if the component is in a valid state, or false if it is contains missing or invalid elements.</returns>
        public override bool CheckValidity()
        {
            bool isValid = false;
            if (BlueprintDefinition != null
            )
            {
                isValid = true;
            }
            return isValid;
        }

        public UnspecifiedComponent() : base(NullLogger.Instance)
        {

        }

        public UnspecifiedComponent(ILogger logger) : base(logger)
        {
        }

    }
}
