// ***********************************************************************
// Assembly         : Deploy.LaunchPad.FileGeneration
// Author           : Nicholas Kellett
// Created          : 11-19-2023
//
// Last Modified By : Nicholas Kellett
// Last Modified On : 01-08-2023
// ***********************************************************************
// <copyright file="UnspecifiedSolution.cs" company="Deploy Software Solutions, inc.">
//     2018-2023 Deploy Software Solutions, inc.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;

namespace Deploy.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents a general solution generated by LaunchPad Framework (often used as a convenience for base services to avoid implementing generics.
    /// </summary>
    [Serializable]
    public partial class UnspecifiedSolution : LaunchPadGeneratedSolution
    {
        /// <summary>
        /// The list of generated unspecified/generic modules that belong to this solution.
        /// </summary>
        /// <value>The modules.</value>
        public virtual IDictionary<string, UnspecifiedModule> Modules { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="UnspecifiedSolution"/> class.
        /// </summary>
        public UnspecifiedSolution() : base()
        {
            var comparer = StringComparer.OrdinalIgnoreCase;
            Modules = new Dictionary<string, UnspecifiedModule>(comparer);
        }
    }
}
