using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a generic component generated by LaunchPad Framework.
    /// </summary>
    [Serializable]
    public partial class LaunchPadGeneratedGenericComponent 
        : LaunchPadGeneratedComponent<LaunchPadGeneratedConfiguration>
    {

        public LaunchPadGeneratedGenericComponent() : base()
        {
        }

    }
}
