using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a general solution generated by LaunchPad Framework (often used as a convenience for base services to avoid implementing generics.
    /// </summary>
    [Serializable]
    public partial class LaunchPadGeneratedGenericSolution
    {
        /// <summary>
        /// The list of generated generic modules that belong to this solution.
        /// </summary>
        public virtual IDictionary<string,LaunchPadGeneratedModule<
            LaunchPadGeneratedConfiguration,
            LaunchPadGeneratedComponent<LaunchPadGeneratedConfiguration>,
            LaunchPadGeneratedConfiguration>
            > Modules { get; set; }

        public LaunchPadGeneratedGenericSolution() : base()
        {
            var comparer = StringComparer.OrdinalIgnoreCase;
            Modules = new Dictionary<string, LaunchPadGeneratedModule<
                                LaunchPadGeneratedConfiguration,
                                LaunchPadGeneratedComponent<LaunchPadGeneratedConfiguration>,
                                LaunchPadGeneratedConfiguration>>(comparer);
        }
    }
}
