using System;

namespace Deploy.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents a static css file generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedStylesheet : LaunchPadGeneratedObjectBase
    {

        public LaunchPadGeneratedStylesheet() : base()
        {

        }
    }
}
