// ***********************************************************************
// Assembly         : Deploy.LaunchPad.FileGeneration
// Author           : Nicholas Kellett
// Created          : 11-19-2023
//
// Last Modified By : Nicholas Kellett
// Last Modified On : 01-08-2023
// ***********************************************************************
// <copyright file="LaunchPadGeneratedApplicationService.cs" company="Deploy Software Solutions, inc.">
//     2018-2023 Deploy Software Solutions, inc.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;

namespace Deploy.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents an application service class generated by LaunchPad Framework, corresponding to a domain entity.
    /// </summary>
    [Serializable]
    public partial class LaunchPadGeneratedApplicationService : LaunchPadGeneratedClassBase
    {
        /// <summary>
        /// The C# Type of the underlying Domain Entity this application service uses (if any)
        /// </summary>
        /// <value>The type of the domain entity.</value>
        public virtual string DomainEntityType { get; set; }

        /// <summary>
        /// Contains a collection of Data Transfer Objects belonging to this component
        /// </summary>
        /// <value>The data transfer objects.</value>
        public virtual IDictionary<string, LaunchPadGeneratedDataTransferObject> DataTransferObjects { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="LaunchPadGeneratedApplicationService"/> class.
        /// </summary>
        public LaunchPadGeneratedApplicationService() : base()
        {
            DomainEntityType = string.Empty;
            var comparer = StringComparer.OrdinalIgnoreCase;
            DataTransferObjects = new Dictionary<string, LaunchPadGeneratedDataTransferObject>(comparer);
        }
    }
}
