// ***********************************************************************
// Assembly         : Deploy.LaunchPad.FileGeneration
// Author           : Nicholas Kellett
// Created          : 11-19-2023
//
// Last Modified By : Nicholas Kellett
// Last Modified On : 06-09-2023
// ***********************************************************************
// <copyright file="LaunchPadGeneratedCustomClassFile .cs" company="Deploy Software Solutions, inc.">
//     2018-2023 Deploy Software Solutions, inc.
// </copyright>
// <summary></summary>
// ***********************************************************************
using Deploy.LaunchPad.Core.Util;
using System;
using System.Collections.Generic;

namespace Deploy.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents a basic class generated by LaunchPad Framework.
    /// </summary>
    [Serializable]
    public partial class LaunchPadGeneratedCustomClassFile : LaunchPadGeneratedClassBase
    {

        /// <summary>
        /// Where this file will be generated
        /// </summary>
        /// <value>The file path.</value>
        public virtual string FilePath { get; set; }


        /// <summary>
        /// Whether the class file actually represents an interface. Defaults to false
        /// </summary>
        /// <value><c>true</c> if this instance is interface; otherwise, <c>false</c>.</value>
        public virtual bool IsInterface { get; set; } = false;

        /// <summary>
        /// Initializes a new instance of the <see cref="LaunchPadGeneratedCustomClassFile"/> class.
        /// </summary>
        public LaunchPadGeneratedCustomClassFile() : base()
        {
            
        }
    }
}
