using Deploy.LaunchPad.Core.Util;
using System;
using System.Collections.Generic;

namespace Deploy.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents a basic class generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedCustomClassFile : LaunchPadGeneratedClassBase
    {

        /// <summary>
        /// The using statements generated in this file.
        /// </summary>
        public virtual string FilePath { get; set; }


        /// <summary>
        /// Whether the class file actually represents an interface. Defaults to false
        /// </summary>
        public virtual bool IsInterface { get; set; } = false;

        public LaunchPadGeneratedCustomClassFile() : base()
        {
            
        }
    }
}
