// ***********************************************************************
// Assembly         : Deploy.LaunchPad.FileGeneration
// Author           : Nicholas Kellett
// Created          : 11-19-2023
//
// Last Modified By : Nicholas Kellett
// Last Modified On : 11-05-2023
// ***********************************************************************
// <copyright file="LaunchPadGeneratedClassBase.cs" company="Deploy Software Solutions, inc.">
//     2018-2023 Deploy Software Solutions, inc.
// </copyright>
// <summary></summary>
// ***********************************************************************
using Deploy.LaunchPad.Core.Util;
using System;
using System.Collections.Generic;

namespace Deploy.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents a basic class generated by LaunchPad Framework.
    /// </summary>
    [Serializable]
    public abstract partial class LaunchPadGeneratedClassBase : LaunchPadGeneratedObjectBase
    {
        /// <summary>
        /// Contains information related to this object's position with a Visual Studio solution
        /// </summary>
        /// <value>The visual studio configuration.</value>
        public virtual VisualStudioClassConfiguration VisualStudioConfig { get; set; }

        /// <summary>
        /// The namespace of the generated item.
        /// </summary>
        /// <value>The namespace.</value>
        public virtual string Namespace { get; set; }


        /// <summary>
        /// The using statements generated in this file.
        /// </summary>
        /// <value>The using statements.</value>
        public virtual HashSet<string> UsingStatements { get; set; }

        /// <summary>
        /// Whether the class is virtual. Defaults to yes to allow partial classes.
        /// </summary>
        /// <value><c>true</c> if this instance is partial; otherwise, <c>false</c>.</value>
        public virtual bool IsPartial { get; set; } = true;

        /// <summary>
        /// Whether the class is static. Defaults to false to prefer instance types.
        /// </summary>
        /// <value><c>true</c> if this instance is static; otherwise, <c>false</c>.</value>
        public virtual bool IsStatic { get; set; } = false;

        /// <summary>
        /// Whether the class is abstract. Defaults to false.
        /// </summary>
        /// <value><c>true</c> if this instance is abstract; otherwise, <c>false</c>.</value>
        public virtual bool IsAbstract { get; set; } = false;

        /// <summary>
        /// The access modifier/level of the class. Defaults to public.
        /// </summary>
        /// <value>The access modifier.</value>
        public LaunchPadGeneratedAccessModifier AccessModifier { get; set; }


        /// <summary>
        /// The dictionary of unique base LaunchPad properties that belong to this class (received through DomainEntity or other base class inheritance).
        /// </summary>
        /// <value>The base properties.</value>
        public virtual IDictionary<string, LaunchPadGeneratedProperty> BaseProperties { get; set; }

        /// <summary>
        /// The dictionary of unique custom properties that belong to this class (that were not inherited).
        /// </summary>
        /// <value>The custom properties.</value>
        public virtual IDictionary<string, LaunchPadGeneratedProperty> CustomProperties { get; set; }

        /// <summary>
        /// Gets the properties.
        /// </summary>
        /// <value>The properties.</value>
        public virtual IDictionary<string, LaunchPadGeneratedProperty> Properties => new DictionaryHelper().MergeDictionaries(BaseProperties, CustomProperties);

        /// <summary>
        /// The dictionary of unique base methods that belong to this class
        /// </summary>
        /// <value>The base methods.</value>
        public virtual IDictionary<string, LaunchPadGeneratedMethod> BaseMethods { get; set; }

        /// <summary>
        /// The dictionary of unique custom methods that belong to this class
        /// </summary>
        /// <value>The custom methods.</value>
        public virtual IDictionary<string, LaunchPadGeneratedMethod> CustomMethods { get; set; }


        /// <summary>
        /// Initializes a new instance of the <see cref="LaunchPadGeneratedClassBase"/> class.
        /// </summary>
        public LaunchPadGeneratedClassBase() : base()
        {
            Namespace = string.Empty;
            UsingStatements = new HashSet<string>();
            var comparer = StringComparer.OrdinalIgnoreCase;
            BaseProperties = new Dictionary<string, LaunchPadGeneratedProperty>(comparer);
            CustomProperties = new Dictionary<string, LaunchPadGeneratedProperty>(comparer);
            BaseMethods = new Dictionary<string, LaunchPadGeneratedMethod>(comparer);
            CustomMethods = new Dictionary<string, LaunchPadGeneratedMethod>(comparer);
            VisualStudioConfig = new VisualStudioClassConfiguration();
            AccessModifier = LaunchPadGeneratedAccessModifier.Public;
        }
    }
}
