using System;
using System.Collections.Generic;

namespace Deploy.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents a C# class method generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedMethod : LaunchPadGeneratedMethodFieldBase
    {
        /// <summary>
        /// The body of the method (code and comment lines within the { and } syntax tokens.
        /// </summary>
        public virtual string Body { get; set; } = string.Empty;

        /// <summary>
        /// The elements of the method comment block.
        /// </summary>
        public virtual LaunchPadGeneratedMethodComments Comments { get; set; }

        /// <summary>
        /// The list of parameters, in order, that this method requires as input. If zero parameters are provided, this is a no-args method.
        /// </summary>
        public IDictionary<string, LaunchPadGeneratedMethodParameter> Parameters;

        /// <summary>
        /// The return type of the method. Default to "void".
        /// </summary>
        public virtual string Returns { get; set; } = "void";

        /// <summary>
        /// Whether the method is async. Defaults to synchronous.
        /// </summary>
        public virtual bool IsAsync { get; set; } = false;

        /// <summary>
        /// Whether the method is virtual. Defaults to yes to allow subclass overriding.
        /// </summary>
        public virtual bool IsVirtual { get; set; } = true;

        /// <summary>
        /// Whether the method is static. Defaults to false to prefer instance methods.
        /// </summary>
        public virtual bool IsStatic { get; set; } = false;

        /// <summary>
        /// The access modifier/level of the method. Defaults to private.
        /// </summary>
        public LaunchPadGeneratedAccessModifier AccessModifier { get; set; }


        public LaunchPadGeneratedMethod() : base()
        {
            var comparer = StringComparer.OrdinalIgnoreCase;
            Parameters = new Dictionary<string, LaunchPadGeneratedMethodParameter>(comparer);
            Comments = new LaunchPadGeneratedMethodComments(Parameters);
            AccessModifier = LaunchPadGeneratedAccessModifier.Private;
        }
    }

}
