// ***********************************************************************
// Assembly         : Deploy.LaunchPad.FileGeneration
// Author           : Nicholas Kellett
// Created          : 11-19-2023
//
// Last Modified By : Nicholas Kellett
// Last Modified On : 03-18-2023
// ***********************************************************************
// <copyright file="LaunchPadGeneratedMethod.cs" company="Deploy Software Solutions, inc.">
//     2018-2023 Deploy Software Solutions, inc.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;

namespace Deploy.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents a C# class method generated by LaunchPad Framework.
    /// </summary>
    [Serializable]
    public partial class LaunchPadGeneratedMethod : LaunchPadGeneratedMethodFieldBase
    {
        /// <summary>
        /// The body of the method (code and comment lines within the { and } syntax tokens.
        /// </summary>
        /// <value>The body.</value>
        public virtual string Body { get; set; } = string.Empty;

        /// <summary>
        /// The elements of the method comment block.
        /// </summary>
        /// <value>The comments.</value>
        public virtual LaunchPadGeneratedMethodComments Comments { get; set; }

        /// <summary>
        /// The list of parameters, in order, that this method requires as input. If zero parameters are provided, this is a no-args method.
        /// </summary>
        public IDictionary<string, LaunchPadGeneratedMethodParameter> Parameters;

        /// <summary>
        /// The return type of the method. Default to "void".
        /// </summary>
        /// <value>The returns.</value>
        public virtual string Returns { get; set; } = "void";

        /// <summary>
        /// Whether the method is async. Defaults to synchronous.
        /// </summary>
        /// <value><c>true</c> if this instance is asynchronous; otherwise, <c>false</c>.</value>
        public virtual bool IsAsync { get; set; } = false;

        /// <summary>
        /// Whether the method is virtual. Defaults to yes to allow subclass overriding.
        /// </summary>
        /// <value><c>true</c> if this instance is virtual; otherwise, <c>false</c>.</value>
        public virtual bool IsVirtual { get; set; } = true;

        /// <summary>
        /// Whether the method is an override. Defaults to false
        /// </summary>
        /// <value><c>true</c> if this instance is override; otherwise, <c>false</c>.</value>
        public virtual bool IsOverride { get; set; } = false;

        /// <summary>
        /// Whether the method is static. Defaults to false to prefer instance methods.
        /// </summary>
        /// <value><c>true</c> if this instance is static; otherwise, <c>false</c>.</value>
        public virtual bool IsStatic { get; set; } = false;


        /// <summary>
        /// Whether the method is abstract. Defaults to false to prefer concrete methods.
        /// </summary>
        /// <value><c>true</c> if this instance is abstract; otherwise, <c>false</c>.</value>
        public virtual bool IsAbstract { get; set; } = false;

        /// <summary>
        /// The access modifier/level of the method. Defaults to private.
        /// </summary>
        /// <value>The access modifier.</value>
        public LaunchPadGeneratedAccessModifier AccessModifier { get; set; }


        /// <summary>
        /// Initializes a new instance of the <see cref="LaunchPadGeneratedMethod"/> class.
        /// </summary>
        public LaunchPadGeneratedMethod() : base()
        {
            var comparer = StringComparer.OrdinalIgnoreCase;
            Parameters = new Dictionary<string, LaunchPadGeneratedMethodParameter>(comparer);
            Comments = new LaunchPadGeneratedMethodComments(Parameters);
            AccessModifier = LaunchPadGeneratedAccessModifier.Private;
        }
    }

}
