using Deploy.LaunchPad.Core.Util;
using System;
using System.Collections.Generic;

namespace Deploy.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents a basic class generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedEnum : LaunchPadGeneratedObjectBase
    {
        
        /// <summary>
        /// Contains information related to this object's position with a Visual Studio solution
        /// </summary>
        public virtual VisualStudioClassConfiguration VisualStudioConfig { get; set; }

        /// <summary>
        /// The namespace of the generated item.
        /// </summary>
        public virtual string Namespace { get; set; }

        /// <summary>
        /// The class and interface inheritance of the enum. 
        /// </summary>
        public virtual string InheritsFrom { get; set; } = "System.Int32";

        /// <summary>
        /// The using statements generated in this file.
        /// </summary>
        public virtual string UsingStatements { get; set; }


        /// <summary>
        /// The access modifier/level of the class. Defaults to public.
        /// </summary>
        public LaunchPadGeneratedAccessModifier AccessModifier { get; set; }


        /// <summary>
        /// The dictionary of unique Enum Items that belong to this enum.
        /// </summary>
        public virtual IDictionary<string, EnumItem> Items { get; set; }

        /// <summary>
        /// Where this file will be generated
        /// </summary>
        public virtual string FilePath { get; set; }


        public LaunchPadGeneratedEnum() : base()
        {
            VisualStudioConfig = new VisualStudioClassConfiguration();
            AccessModifier = LaunchPadGeneratedAccessModifier.Public;
            Namespace = string.Empty;
            UsingStatements = string.Empty;
            var comparer = StringComparer.OrdinalIgnoreCase;
            Items = new Dictionary<string, EnumItem>(comparer);
        }
    }

    public partial class EnumItem
    {
        public virtual string Name { get; set;}

        public virtual int Value { get; set;}

        public virtual string Description { get; set;} 

        public EnumItem()
        {

        }
    }

}
