using System;

namespace Deploy.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents a C# property generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedProperty : LaunchPadGeneratedMethodParameter
    {

        public virtual bool IsReadonly { get; set; }

        public virtual bool IsVirtual { get; set; }

        public LaunchPadGeneratedProperty() : base()
        {
            IsReadonly = false;
            IsVirtual = false;
        }

    }

}
