using System;
using System.Collections.Generic;

namespace Deploy.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents a domain entity class generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedDomainEntity : LaunchPadGeneratedClassBase
    {

        /// <summary>
        /// Contains a collection of Data Transfer Objects belonging to this domain entity
        /// </summary>
        public virtual IDictionary<string, LaunchPadGeneratedDataTransferObject> DataTransferObjects { get; set; }

        public string DbContextEntityFrameworkMappingStatements { get; set; }= string.Empty;

        public LaunchPadGeneratedDomainEntity() : base()
        {
            var comparer = StringComparer.OrdinalIgnoreCase;
            DataTransferObjects = new Dictionary<string, LaunchPadGeneratedDataTransferObject>(comparer);
        }
    }
}
