using System;
using System.Collections.Generic;

namespace Deploy.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents the comments for a C# class method generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedMethodComments
    {
        /// <summary>
        /// The summary text of the method comments.
        /// </summary>
        public virtual string Summary { get; set; } = string.Empty;

        /// <summary>
        /// The list of parameters, in order, that this method requires as input. If zero parameters are provided, this is a no-args method.
        /// The LaunchPadGeneratedMethodParameter "name" property will be the key and name of the param element, 
        /// and the LaunchPadGeneratedMethodParameter description will be the text.
        /// </summary>
        public IDictionary<string, LaunchPadGeneratedMethodParameter> Parameters;

        /// <summary>
        /// The return text of the method comments (if any).
        /// </summary>
        public virtual string Returns { get; set; } = String.Empty;

        protected LaunchPadGeneratedMethodComments() : base()
        {
            var comparer = StringComparer.OrdinalIgnoreCase;
            Parameters = new Dictionary<string, LaunchPadGeneratedMethodParameter>(comparer);
        }

        public LaunchPadGeneratedMethodComments(IDictionary<string, LaunchPadGeneratedMethodParameter> parameters) : base()
        {
            if (parameters != null)
            {
                Parameters = parameters;
            }
            else
            {
                var comparer = StringComparer.OrdinalIgnoreCase;
                Parameters = new Dictionary<string, LaunchPadGeneratedMethodParameter>(comparer);
            }
        }
    }

}
