using Deploy.LaunchPad.Core.Util;
using System;
using System.Collections.Generic;

namespace Deploy.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents a basic class generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public abstract partial class LaunchPadGeneratedCustomClassFile : LaunchPadGeneratedClassBase
    {

        /// <summary>
        /// The using statements generated in this file.
        /// </summary>
        public virtual string FilePath { get; set; }


        public LaunchPadGeneratedCustomClassFile() : base()
        {
            
        }
    }
}
