using DeploySoftware.LaunchPad.Core.Util;
using System;
using System.Collections.Generic;
using System.Text;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a C# DTO generated by LaunchPad Framework.
    /// </summary>
    [Serializable]
    public partial class LaunchPadGeneratedDataTransferObject : LaunchPadGeneratedObjectBase
    {

        /// <summary>
        /// Contains information related to this object's position with a Visual Studio solution
        /// </summary>
        public virtual VisualStudioClassConfiguration VisualStudioConfig { get; set; }

        /// <summary>
        /// The dictionary of unique base properties that belong to this DTO (which may be identical to the domain entity, or not)
        /// </summary>
        public virtual IDictionary<string, LaunchPadGeneratedProperty> BaseProperties { get; set; }

        /// <summary>
        /// The dictionary of unique custom properties that belong to this DTO (which may be identical to the domain entity, or not)
        /// </summary>
        public virtual IDictionary<string, LaunchPadGeneratedProperty> CustomProperties { get; set; }

        public virtual IDictionary<string, LaunchPadGeneratedProperty> Properties => new DictionaryHelper().MergeDictionaries(BaseProperties, CustomProperties);

        /// <summary>
        /// The namespace of the generated item.
        /// </summary>
        public virtual string Namespace { get; set; }

        /// <summary>
        /// The class and interface inheritance of the item (everything after the colon ':' in the definition)
        /// </summary>
        public virtual string InheritsFrom { get; set; }

        /// <summary>
        /// The ID of the property set which applies to this DTO
        /// </summary>
        public virtual string PropertySetId { get; set; }

        public LaunchPadGeneratedDataTransferObject() : base()
        {
            Annotations = string.Empty;
            Namespace = string.Empty;
            InheritsFrom = string.Empty;
            var comparer = StringComparer.OrdinalIgnoreCase;
            BaseProperties = new Dictionary<string, LaunchPadGeneratedProperty>(comparer);
            CustomProperties = new Dictionary<string, LaunchPadGeneratedProperty>(comparer);
            VisualStudioConfig = new VisualStudioClassConfiguration();
            PropertySetId = string.Empty;
        }
    }
}
