using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a set of related static web pages or resources (.htm or CSS etc) generated by LaunchPad Framework.
    /// </summary>
    [Serializable]
    public partial class LaunchPadGeneratedStaticWebModule : 
        LaunchPadGeneratedModule<LaunchPadGeneratedStaticWebModuleConfiguration, 
            LaunchPadGeneratedComponent<LaunchPadGeneratedConfiguration>,
            LaunchPadGeneratedConfiguration>
    {
        /// <summary>
        /// The list of static web pages that belong to this module.
        /// </summary>
        public virtual IList<LaunchPadGeneratedStaticWebPage> StaticWebPages { get; set; }

        /// <summary>
        /// The list of static stylesheets (.css) that belong to this module.
        /// </summary>
        public virtual IList<LaunchPadGeneratedStaticStylesheet> Stylesheets { get; set; }

        public LaunchPadGeneratedStaticWebModule() : base()
        {
            StaticWebPages = new List<LaunchPadGeneratedStaticWebPage>();
            Stylesheets = new List<LaunchPadGeneratedStaticStylesheet>();
        }

    }
}
