using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DeploySoftware.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents an AspNetBoilerplate "module" that is generated by LaunchPad Framework and provides functionality in the .NET application.
    /// Although the name sounds similar to LaunchPad framework's "modules", the concept is more like our "Components" since it contains very low-level, composable functionality.
    /// see https://aspnetboilerplate.com/Pages/Documents/Module-System
    /// </summary>    
    [Serializable]
    public partial class AbpModuleDefinition
    {
        public string Name { get; set; }

        public string Path { get; set; }

        public string InheritsFrom { get; set; }

        public IDictionary<string, string> DependsOnModules { get; set; }


        public AbpModuleDefinition()
        {
            Name = string.Empty;
            Path = string.Empty;
            InheritsFrom = string.Empty;
            var comparer = StringComparer.OrdinalIgnoreCase;
            DependsOnModules = new Dictionary<string, string>(comparer);
        }

    }
}
