using Castle.Core.Logging;
using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents a Visual Studio component generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class VisualStudioComponent
        : LaunchPadGeneratedComponent<VisualStudioBlueprintDefinitionSettings, VisualStudioBlueprintDefinitionInstructions>, 
        IVisualStudioComponent
    {

        /// <summary>
        /// Contains a dictionary of Application Services belonging to this component, keyed by the application service name
        /// </summary>
        public virtual IDictionary<string, LaunchPadGeneratedApplicationService> ApplicationServices { get; set; }


        /// <summary>
        /// Contains a dictionary of Domain Entities belonging to this component, keyed by the domain entity name
        /// </summary>
        public virtual IDictionary<string, LaunchPadGeneratedDomainEntity> DomainEntities { get; set; }

        /// <summary>
        /// Describes the overall coding/environment infrastructure in which this element exists 
        /// (ex which version of ABP framework, which cloud provider)
        /// </summary>
        public virtual ISoftwareInfrastructure SoftwareInfrastructure { get; set; }

        /// <summary>
        /// Returns a bool indicating if the component is currently in a valid or invalid state.
        /// </summary>
        /// <returns>True if the component is in a valid state, or false if it is contains missing or invalid elements.</returns>
        public override bool CheckValidity()
        {
            bool isValid = false;
            if (BlueprintDefinition != null
                && ApplicationServices != null && ApplicationServices.Count > 0
                && DomainEntities != null && DomainEntities.Count > 0
            )
            {
                isValid = true;
            }
            return isValid;
        }

        public VisualStudioComponent() : base(NullLogger.Instance)
        {
            var comparer = StringComparer.OrdinalIgnoreCase;
            DomainEntities = new Dictionary<string, LaunchPadGeneratedDomainEntity>(comparer);
            ApplicationServices = new Dictionary<string, LaunchPadGeneratedApplicationService>(comparer);
        }

        public VisualStudioComponent(ILogger logger) : base(logger)
        {
            var comparer = StringComparer.OrdinalIgnoreCase;
            DomainEntities = new Dictionary<string, LaunchPadGeneratedDomainEntity>(comparer);
            ApplicationServices = new Dictionary<string, LaunchPadGeneratedApplicationService>(comparer);
        }
    }
}
