// ***********************************************************************
// Assembly         : Deploy.LaunchPad.Core.Abp
// Author           : Nicholas Kellett
// Created          : 11-19-2023
//
// Last Modified By : Nicholas Kellett
// Last Modified On : 01-08-2023
// ***********************************************************************
// <copyright file="Deploy.LaunchPad.Core.Abp.Resources.Designer.cs" company="Deploy Software Solutions, inc.">
//     2018-2024 Deploy Software Solutions, inc.
// </copyright>
// <summary></summary>
// ***********************************************************************

namespace Deploy.LaunchPad.Core.Abp {
    using System;


    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Deploy_LaunchPad_Core_Abp_Resources {

        /// <summary>
        /// The resource man
        /// </summary>
        private static global::System.Resources.ResourceManager resourceMan;

        /// <summary>
        /// The resource culture
        /// </summary>
        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Initializes a new instance of the <see cref="Deploy_LaunchPad_Core_Abp_Resources"/> class.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Deploy_LaunchPad_Core_Abp_Resources() {
        }

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        /// <value>The resource manager.</value>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Deploy.LaunchPad.Core.Abp.Deploy.LaunchPad.Core.Abp.Resources", typeof(Deploy_LaunchPad_Core_Abp_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        /// <value>The culture.</value>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Executed background job: '{0}'.
        /// </summary>
        /// <value>The logger debug background job executed.</value>
        public static string Logger_Debug_BackgroundJob_Executed {
            get {
                return ResourceManager.GetString("Logger_Debug_BackgroundJob_Executed", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Executing background job: '{0}'.
        /// </summary>
        /// <value>The logger debug background job executing.</value>
        public static string Logger_Debug_BackgroundJob_Executing {
            get {
                return ResourceManager.GetString("Logger_Debug_BackgroundJob_Executing", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Started background worker: '{0}'.
        /// </summary>
        /// <value>The logger debug background worker started.</value>
        public static string Logger_Debug_BackgroundWorker_Started {
            get {
                return ResourceManager.GetString("Logger_Debug_BackgroundWorker_Started", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Starting background worker: '{0}'.
        /// </summary>
        /// <value>The logger debug background worker starting.</value>
        public static string Logger_Debug_BackgroundWorker_Starting {
            get {
                return ResourceManager.GetString("Logger_Debug_BackgroundWorker_Starting", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Stopped background worker: '{0}'.
        /// </summary>
        /// <value>The logger debug background worker stopped.</value>
        public static string Logger_Debug_BackgroundWorker_Stopped {
            get {
                return ResourceManager.GetString("Logger_Debug_BackgroundWorker_Stopped", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Stopping background worker: '{0}'.
        /// </summary>
        /// <value>The logger debug background worker stopping.</value>
        public static string Logger_Debug_BackgroundWorker_Stopping {
            get {
                return ResourceManager.GetString("Logger_Debug_BackgroundWorker_Stopping", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Finished waiting to stop background worker: '{0}'.
        /// </summary>
        /// <value>The logger debug background worker waited to stop.</value>
        public static string Logger_Debug_BackgroundWorker_WaitedToStop {
            get {
                return ResourceManager.GetString("Logger_Debug_BackgroundWorker_WaitedToStop", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Waiting to stop background worker: '{0}'.
        /// </summary>
        /// <value>The logger debug background worker waiting to stop.</value>
        public static string Logger_Debug_BackgroundWorker_WaitingToStop {
            get {
                return ResourceManager.GetString("Logger_Debug_BackgroundWorker_WaitingToStop", resourceCulture);
            }
        }
    }
}
