using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a component generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedComponent<TComponentConfig> 
        : LaunchPadGeneratedObjectBase, ILaunchPadGeneratedComponent<TComponentConfig>
        where TComponentConfig: LaunchPadGeneratedConfiguration,new()
    {
        public TComponentConfig Config { get; set; }

        /// <summary>
        /// The id type of the entities (if any).
        /// </summary>
        public virtual string EntityIdType { get; set; }

        public LaunchPadGeneratedComponent() : base()
        {
            Config = new TComponentConfig();
            EntityIdType = string.Empty;
        }
    }
}
