using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a solution generated by LaunchPad Framework.
    /// </summary>
    [Serializable]
    public abstract partial class LaunchPadGeneratedSolutionBase : LaunchPadGeneratedObjectBase, ILaunchPadGeneratedSolution
    {
        /// <summary>
        /// Contains information related to this object's Visual Studio solution (.sln)
        /// </summary>
        public virtual ILaunchPadGeneratedSolutionConfiguration Config { get; set; }


        /// <summary>
        /// The set of components that belong to this module.
        /// </summary>
        public virtual IDictionary<string, ILaunchPadGeneratedModule> Modules { get; set; }

        public LaunchPadGeneratedSolutionBase() : base()
        {
        }
    }
}
