using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a solution generated by LaunchPad Framework.
    /// </summary>
    [Serializable]
    public partial class LaunchPadGeneratedSolution : LaunchPadGeneratedObjectBase
    {
        
        /// <summary>
        /// The version of this module
        /// </summary>
        public string Version { get; set; }

        /// <summary>
        /// The list of generated Visual Studio modules that belong to this solution.
        /// </summary>
        public IList<LaunchPadGeneratedVisualStudioModule> VisualStudioModules { get; set; }

        /// <summary>
        /// The list of generated document set modules that belong to this solution.
        /// </summary>
        public IList<LaunchPadGeneratedStaticWebModule> DocumentSetModules { get; set; }

        /// <summary>
        /// The list of generated static web resource modules that belong to this solution.
        /// </summary>
        public IList<LaunchPadGeneratedStaticWebModule> StaticWebModules { get; set; }

        public LaunchPadGeneratedSolution() : base()
        {
            Version = string.Empty;
            VisualStudioModules = new List<LaunchPadGeneratedVisualStudioModule>();
            DocumentSetModules = new List<LaunchPadGeneratedStaticWebModule>();
            StaticWebModules = new List<LaunchPadGeneratedStaticWebModule>();
        }
    }
}
