using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a solution generated by LaunchPad Framework.
    /// </summary>
    [Serializable]
    public abstract partial class LaunchPadGeneratedSolutionBase : LaunchPadGeneratedObjectBase
    {
        
        /// <summary>
        /// The version of this module
        /// </summary>
        public string Version { get; set; }


        public LaunchPadGeneratedSolutionBase() : base()
        {
            Version = string.Empty;
        }
    }
}
