using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a solution generated by LaunchPad Framework.
    /// </summary>
    [Serializable]
    public partial class LaunchPadGeneratedSolution : LaunchPadGeneratedObjectBase
    {

        /// <summary>
        /// Contains configuration information related to this object's solution
        /// </summary>
        public virtual LaunchPadGeneratedSolutionConfiguration Config { get; set; }

        public LaunchPadGeneratedSolution() : base()
        {
            Config = new LaunchPadGeneratedSolutionConfiguration();
        }
    }
}
