using System;
using System.Collections.Generic;
using System.Text;

namespace DeploySoftware.LaunchPad.Core.Util
{ 
    /// <summary>
  /// Represents a C# DTO generated by LaunchPad Framework.
  /// </summary>
    public class LaunchPadGeneratedDataTransferObject : LaunchPadGeneratedClass
    {



    }
}
