using System;
using System.Collections.Generic;
using System.Text;

namespace DeploySoftware.LaunchPad.Core.Util
{
    /// <summary>
    /// Represents a C# property generated by LaunchPad Framework.
    /// </summary>
    public partial class LaunchPadGeneratedProperty : LaunchPadGeneratedMethodParameter
    {
        
        public bool IsReadonly { get; set; }

        public bool IsVirtual { get; set; }

        public LaunchPadGeneratedProperty() : base()
        {
            IsReadonly = false;
            IsVirtual = false;
        }

    }

}
