using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.Util
{
    /// <summary>
    /// Represents a component generated by LaunchPad Framework.
    /// </summary>
    public class LaunchPadGeneratedComponent : LaunchPadGeneratedObjectBase
    {
        /// <summary>
        /// Contains information related to this object's position with a Visual Studio solution
        /// </summary>
        public LaunchPadGeneratedVisualStudioConfiguration VisualStudioConfig { get; set; }

        /// <summary>
        /// The prefix to apply to the name (if any).
        /// </summary>
        public string NamePrefix { get; set; }

        /// <summary>
        /// The suffix to apply to the name (if any).
        /// </summary>
        public string NameSuffix { get; set; }

        /// <summary>
        /// The namespace of the generated item.
        /// </summary>
        public string Namespace { get; set; }

        /// <summary>
        /// The resulting C# type of the object when generated.
        /// </summary>
        public string ClassType { get; set; }

        /// <summary>
        /// The id type of this component's primary key.
        /// </summary>
        public string IdType { get; set; }

        /// <summary>
        /// The id type of the entities (if any).
        /// </summary>
        public string EntityIdType { get; set; }

        /// <summary>
        /// The list of domain entities that belong to this component (if any).
        /// </summary>
        public IList<LaunchPadGeneratedClass> DomainEntities { get; set; }

        public LaunchPadGeneratedComponent()
        {
            ClassType = string.Empty; 
            NamePrefix = string.Empty;
            NameSuffix = string.Empty;
            Namespace = string.Empty;
            IdType = string.Empty;
            EntityIdType = string.Empty;
            DomainEntities = new List<LaunchPadGeneratedClass>();
            VisualStudioConfig = new LaunchPadGeneratedVisualStudioConfiguration();
        }
    }
}
