using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.Util
{
    /// <summary>
    /// Represents a C# class generated by LaunchPad Framework.
    /// </summary>
    public class LaunchPadGeneratedClass : LaunchPadGeneratedObjectBase
    {
        /// <summary>
        /// Contains information related to this object's position with a Visual Studio solution
        /// </summary>
        public LaunchPadGeneratedVisualStudioConfiguration VisualStudioConfig { get; set; }

        /// <summary>
        /// The resulting C# type of the object when generated.
        /// </summary>
        public string ClassType { get; set; }

        /// <summary>
        /// The prefix to apply to the name (if any).
        /// </summary>
        public string NamePrefix { get; set; }

        /// <summary>
        /// The suffix to apply to the name (if any).
        /// </summary>
        public string NameSuffix { get; set; }

        /// <summary>
        /// The class and interface inheritance of the item (everything after the colon ':' in the definition)
        /// </summary>
        public string InheritsFrom { get; set; }
       
        /// <summary>
        /// The namespace of the generated item.
        /// </summary>
        public string Namespace { get; set; }

        /// <summary>
        /// The id type of the primary key.
        /// </summary>
        public string IdType { get; set; }

        /// <summary>
        /// The list of base LaunchPad properties that belong to this class (received through DomainEntity or other base class inheritance).
        /// </summary>
        public IList<LaunchPadGeneratedProperty> BaseProperties { get; set; }

        /// <summary>
        /// The list of custom properties that belong to this class (that were not inherited).
        /// </summary>
        public IList<LaunchPadGeneratedProperty> CustomProperties { get; set; }

        /// <summary>
        /// The list of base methods that belong to this class (received through DomainEntity or other base class inheritance).
        /// </summary>
        public IList<LaunchPadGeneratedMethod> BaseMethods { get; set; }

        /// <summary>
        /// The list of custom methods that belong to this class (that were not inherited).
        /// </summary>
        public IList<LaunchPadGeneratedMethod> CustomMethods { get; set; }

        public LaunchPadGeneratedClass()
        {
            ClassType = string.Empty;
            NamePrefix = string.Empty;
            NameSuffix = string.Empty;
            InheritsFrom = string.Empty;
            Namespace = string.Empty;
            IdType = string.Empty;
            BaseProperties = new List<LaunchPadGeneratedProperty>();
            CustomProperties = new List<LaunchPadGeneratedProperty>();
            BaseMethods = new List<LaunchPadGeneratedMethod>();
            CustomMethods = new List<LaunchPadGeneratedMethod>();
            VisualStudioConfig = new LaunchPadGeneratedVisualStudioConfiguration();
        }
    }
}
