// ***********************************************************************
// Assembly         : Deploy.LaunchPad.FileGeneration
// Author           : Nicholas Kellett
// Created          : 11-19-2023
//
// Last Modified By : Nicholas Kellett
// Last Modified On : 01-08-2023
// ***********************************************************************
// <copyright file="WebAppModule.cs" company="Deploy Software Solutions, inc.">
//     2018-2023 Deploy Software Solutions, inc.
// </copyright>
// <summary></summary>
// ***********************************************************************
using Castle.Core.Logging;
using System;
using System.Collections.Generic;

namespace Deploy.LaunchPad.FileGeneration.Structure
{
    /// <summary>
    /// Represents a module generated by LaunchPad Framework that contains
    /// API/middleware/backend component, at least one web client component, and possible documentation component.
    /// </summary>
    [Serializable]
    public partial class WebAppModule : LaunchPadGeneratedModule<WebAppModuleSettings>, IWebAppModule
    {

        /// <summary>
        /// Gets or sets the web API.
        /// </summary>
        /// <value>The web API.</value>
        public virtual VisualStudioComponent WebApi { get; set; }

        /// <summary>
        /// Gets or sets the web clients.
        /// </summary>
        /// <value>The web clients.</value>
        public virtual IDictionary<string, WebClientComponent> WebClients { get; set; }


        /// <summary>
        /// Describes the overall coding/environment infrastructure in which this element exists
        /// (ex which version of ABP framework, which cloud provider)
        /// </summary>
        /// <value>The software infrastructure.</value>
        public virtual ISoftwareInfrastructure SoftwareInfrastructure { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebAppModule"/> class.
        /// </summary>
        public WebAppModule() : base(NullLogger.Instance)
        {
            Settings = new WebAppModuleSettings();
            WebApi = new VisualStudioComponent(NullLogger.Instance);
            var comparer = StringComparer.OrdinalIgnoreCase;
            WebClients = new Dictionary<string, WebClientComponent>(comparer);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebAppModule"/> class.
        /// </summary>
        /// <param name="logger">The logger.</param>
        public WebAppModule(ILogger logger) : base(logger)
        {
            Settings = new WebAppModuleSettings();
            WebApi = new VisualStudioComponent(logger);
            var comparer = StringComparer.OrdinalIgnoreCase;
            WebClients = new Dictionary<string, WebClientComponent>(comparer);
        }
    }
}
