// Initially generated by quicktype https://github.com/quicktype/quicktype under the Apache 2 license.
// using the json schema found here: https://geojson.org/schema/Feature.json
// 
namespace Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson.Geometries
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson;
    using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson.Types;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Feature : IAmAGeometryType
    {
        [JsonProperty("bbox", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public virtual List<double> Bbox { get; set; }

        [JsonProperty("geometry", Required = Required.AllowNull)]
        public virtual Geometry Geometry { get; set; }

        [JsonProperty("id", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public virtual GeoJsonId? Id { get; set; }

        [JsonProperty("properties", Required = Required.AllowNull)]
        public virtual Dictionary<string, dynamic> Properties { get; set; }

        [JsonProperty("type", Required = Required.Always)]
        public virtual FeatureType Type { get; set; }
        public static Feature FromJson(string json) => JsonConvert.DeserializeObject<Feature>(json, FeatureConverter.Settings);
    }

    public enum GeoJsonPointType { GeometryCollection, LineString, MultiLineString, MultiPoint, MultiPolygon, Point, Polygon };

    public enum FeatureType { Feature };


    public static class SerializeFeature
    {
        public static string ToJson(this Feature self) => JsonConvert.SerializeObject(self, FeatureConverter.Settings);
    }

    internal static class FeatureConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                GeometryTypeConverter.Singleton,
                GeoJsonPointTypeConverter.Singleton,
                GeoJsonIdConverter.Singleton,
                FeatureTypeConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

}
