// Initially generated by quicktype https://github.com/quicktype/quicktype under the Apache 2 license.
// using the json schema found here: https://geojson.org/schema/Feature.json
// 
namespace Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson.Geometries
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson;
    using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson.Types;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    [Serializable]
    public partial class Feature : GeoJsonGeometryTypeBase
    {

        [JsonProperty("geometry", Required = Required.AllowNull)]
        public virtual Geometry Geometry { get; set; }

        [JsonProperty("id", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public virtual GeoJsonId? Id { get; set; }

        [JsonProperty("properties", Required = Required.AllowNull)]
        public virtual Dictionary<string, dynamic> Properties { get; set; }

        [JsonProperty("type", Required = Required.Always)]
        public virtual GeoJsonType Type { get; set; } = GeoJsonType.Feature;

        public static Feature FromJson(string json) => JsonConvert.DeserializeObject<Feature>(json, FeatureConverter.Settings);


        public Feature() : base()
        {

        }
    }


    public static class SerializeFeature
    {
        public static string ToJson(this Feature self) => JsonConvert.SerializeObject(self, FeatureConverter.Settings);
    }

    internal static class FeatureConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                GeoJsonPointTypeConverter.Singleton,
                GeoJsonIdConverter.Singleton,
                GeoJsonTypeConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

}
