// Initially generated by quicktype https://github.com/quicktype/quicktype under the Apache 2 license.
// using the json schema found here: https://geojson.org/schema/FeatureCollection.json
// 

namespace Deploy.LaunchPad.Core.GeoJson
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson;
    using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson.Geometries;
    using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson.Types;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    [Serializable]
    public partial class FeatureCollection : GeoJsonGeometryTypeBase
    {

        [JsonProperty("features", Required = Required.Always)]
        public virtual List<Feature> Features { get; set; }

        [JsonProperty("type", Required = Required.Always)]
        public virtual GeoJsonType Type { get; set; } = GeoJsonType.FeatureCollection;


        public FeatureCollection() : base()
        {

        }

        public static FeatureCollection FromJson(string json) => JsonConvert.DeserializeObject<FeatureCollection>(json, Deploy.LaunchPad.Core.GeoJson.FeatureCollectionConverter.Settings);
    }

    
    public static class SerializeFeatureCollection
    {
        public static string ToJson(this FeatureCollection self) => JsonConvert.SerializeObject(self, Deploy.LaunchPad.Core.GeoJson.FeatureCollectionConverter.Settings);
    }

    internal static class FeatureCollectionConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                GeoJsonIdConverter.Singleton,
                GeoJsonTypeConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    
}
