// Initially generated by quicktype https://github.com/quicktype/quicktype under the Apache 2 license.
// using the json schema found here: https://geojson.org/schema/Geometry.json
// 

namespace Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson.Geometries
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Deploy.LaunchPad.Core.Domain;
    using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson;
    using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson.Types;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Geometry : IAmAGeometryType
    {
        [JsonProperty("bbox", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public virtual List<double> Bbox { get; set; }

        [JsonProperty("coordinates", Required = Required.Always)]
        public virtual List<IGeographicPosition> Coordinates { get; set; }

        [JsonProperty("type", Required = Required.Always)]
        public virtual GeometryType Type { get; set; }

        public Geometry()
        {
            Coordinates = new List<IGeographicPosition>();
        }

        public static Geometry FromJson(string json) => JsonConvert.DeserializeObject<Geometry>(json, GeometryConverter.Settings);
    }

    public static class SerializeGeometry
    {
        public static string ToJson(this Geometry self) => JsonConvert.SerializeObject(self, GeometryConverter.Settings);
    }

    internal static class GeometryConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                GeometryTypeConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }


}
