// Initially generated by quicktype https://github.com/quicktype/quicktype under the Apache 2 license.
// using the json schema found here: https://geojson.org/schema/LineString.json
// 

namespace Deploy.LaunchPad.Core.GeoJson
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson;
    using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson.Geometries;
    using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson.Types;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    [Serializable]
    public partial class LineString : GeoJsonGeometryTypeBase
    {

        [JsonProperty("coordinates", Required = Required.Always)]
        public virtual List<List<double>> Coordinates { get; set; }

        [JsonProperty("type", Required = Required.Always)]
        public virtual GeoJsonType Type { get; set; } = GeoJsonType.LineString;


        public LineString() : base()
        {

        }

        public static LineString FromJson(string json) => JsonConvert.DeserializeObject<LineString>(json, Deploy.LaunchPad.Core.GeoJson.LineStringConverter.Settings);
    }


    public static class SerializeLineString
    {
        public static string ToJson(this LineString self) => JsonConvert.SerializeObject(self, Deploy.LaunchPad.Core.GeoJson.LineStringConverter.Settings);
    }

    internal static class LineStringConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                GeoJsonTypeConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

}
