// Initially generated by quicktype https://github.com/quicktype/quicktype under the Apache 2 license.
// using the json schema found here: https://geojson.org/schema/MultiPolygon.json
// 

namespace Deploy.LaunchPad.Core.GeoJson
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson;
    using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson.Geometries;
    using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson.Types;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    [Serializable]
    public partial class MultiPolygon : GeoJsonGeometryTypeBase
    {

        [JsonProperty("coordinates", Required = Required.Always)]
        public virtual List<List<List<List<double>>>> Coordinates { get; set; }

        [JsonProperty("type", Required = Required.Always)]
        public virtual GeoJsonType Type { get; set; } = GeoJsonType.MultiPolygon;

        public MultiPolygon() : base()
        {

        }

        public static MultiPolygon FromJson(string json) => JsonConvert.DeserializeObject<MultiPolygon>(json, Deploy.LaunchPad.Core.GeoJson.MultiPolygonConverter.Settings);
    }

    public static class SerializeMultiPolygon
    {
        public static string ToJson(this MultiPolygon self) => JsonConvert.SerializeObject(self, Deploy.LaunchPad.Core.GeoJson.MultiPolygonConverter.Settings);
    }

    internal static class MultiPolygonConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                GeoJsonTypeConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

}
