// Initially generated by quicktype https://github.com/quicktype/quicktype under the Apache 2 license.
// using the json schema found here: https://geojson.org/schema/MultiPolygon.json
// 

namespace Deploy.LaunchPad.Core.GeoJson
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson;
    using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson.Types;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class MultiPolygon : IAmAGeometryType
    {
        [JsonProperty("bbox", Required = Required.DisallowNull, NullValueHandling = NullValueHandling.Ignore)]
        public virtual List<double> Bbox { get; set; }

        [JsonProperty("coordinates", Required = Required.Always)]
        public virtual List<List<List<List<double>>>> Coordinates { get; set; }

        [JsonProperty("type", Required = Required.Always)]
        public virtual GeometryType Type { get; set; } = GeometryType.MultiPolygon;
    }

    public partial class MultiPolygon
    {
        public static MultiPolygon FromJson(string json) => JsonConvert.DeserializeObject<MultiPolygon>(json, Deploy.LaunchPad.Core.GeoJson.MultiPolygonConverter.Settings);
    }

    public static class SerializeMultiPolygon
    {
        public static string ToJson(this MultiPolygon self) => JsonConvert.SerializeObject(self, Deploy.LaunchPad.Core.GeoJson.MultiPolygonConverter.Settings);
    }

    internal static class MultiPolygonConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                GeometryTypeConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

}
