// Initially generated by quicktype https://github.com/quicktype/quicktype under the Apache 2 license.
// using the json schema found here: https://geojson.org/schema/MultiPoint.json
// 
namespace Deploy.LaunchPad.Core.GeoJson
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson;
    using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson.Geometries;
    using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson.Types;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    [Serializable]
    public partial class MultiPoint : GeoJsonGeometryTypeBase
    {

        [JsonProperty("coordinates", Required = Required.Always)]
        public virtual List<List<double>> Coordinates { get; set; }

        [JsonProperty("type", Required = Required.Always)]
        public virtual GeoJsonType Type { get; set; } = GeoJsonType.MultiPoint;


        public MultiPoint() : base()
        {

        }

        public static MultiPoint FromJson(string json) => JsonConvert.DeserializeObject<MultiPoint>(json, Deploy.LaunchPad.Core.GeoJson.MultiPointConverter.Settings);
    }



    public static class SerializeMultiPoint
    {
        public static string ToJson(this MultiPoint self) => JsonConvert.SerializeObject(self, Deploy.LaunchPad.Core.GeoJson.MultiPointConverter.Settings);
    }

    internal static class MultiPointConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                GeoJsonTypeConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

}
