// Initially generated by quicktype https://github.com/quicktype/quicktype under the Apache 2 license.
// 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Deploy.LaunchPad.Core.Geospatial.STAC
{

    public enum OrganizationRole
    {
        Host = 0,
        Licensor = 1,
        Processor = 2,
        Producer = 3
    };
}
