// Initially generated by quicktype https://github.com/quicktype/quicktype under the Apache 2 license.
// 

namespace Deploy.LaunchPad.Core.STAC
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class StacLicensing
    {
        [JsonProperty("license", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string License { get; set; }
    }

    public partial class StacLicensing
    {
        public static StacLicensing FromJson(string json) => JsonConvert.DeserializeObject<StacLicensing>(json, Deploy.LaunchPad.Core.STAC.StacLicensingConverter.Settings);
    }

    public static class SerializeStacLicensing
    {
        public static string ToJson(this StacLicensing self) => JsonConvert.SerializeObject(self, Deploy.LaunchPad.Core.STAC.StacLicensingConverter.Settings);
    }

    internal static class StacLicensingConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
