// Initially generated by quicktype https://github.com/quicktype/quicktype under the Apache 2 license.
// 

namespace Deploy.LaunchPad.Core.STAC
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Deploy.LaunchPad.Core.Domain.Geography.STAC;
    using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson;
    using Deploy.LaunchPad.Core.GeoJson;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>
    /// This object represents the metadata for an item in a SpatioTemporal Asset Catalog.
    /// </summary>
    public partial class StacItem
    {
        [JsonProperty("bbox", NullValueHandling = NullValueHandling.Ignore)]
        public virtual List<double> Bbox { get; set; }

        [JsonProperty("geometry")]
        public virtual GeoJsonDefinition Geometry { get; set; }

        /// <summary>
        /// Provider item ID
        /// </summary>
        [JsonProperty("id")]
        [JsonConverter(typeof(MinMaxLengthCheckConverter))]
        public virtual string Id { get; set; }

        [JsonProperty("properties")]
        public virtual CommonMetadata Properties { get; set; }

        [JsonProperty("type")]
        public virtual StacItemType Type { get; set; }

        [JsonProperty("assets")]
        public virtual Dictionary<string, StacAsset> Assets { get; set; }

        /// <summary>
        /// Links to item relations
        /// </summary>
        [JsonProperty("links")]
        public virtual List<StacLink> Links { get; set; }

        [JsonProperty("stac_extensions", NullValueHandling = NullValueHandling.Ignore)]
        public virtual List<string> StacExtensions { get; set; }

        [JsonProperty("stac_version")]
        public virtual string StacVersion { get; set; }
    }



    public partial class CommonMetadata
    {
        /// <summary>
        /// Detailed multi-line description to fully explain the Item.
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string Description { get; set; }

        /// <summary>
        /// A human-readable title describing the Item.
        /// </summary>
        [JsonProperty("title", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string Title { get; set; }

        [JsonProperty("created", NullValueHandling = NullValueHandling.Ignore)]
        public virtual DateTimeOffset? Created { get; set; }

        /// <summary>
        /// The searchable date/time of the assets, in UTC (Formatted in RFC 3339)
        /// </summary>
        [JsonProperty("datetime")]
        public virtual DateTimeOffset? Datetime { get; set; }

        /// <summary>
        /// The searchable end date/time of the assets, in UTC (Formatted in RFC 3339)
        /// </summary>
        [JsonProperty("end_datetime", NullValueHandling = NullValueHandling.Ignore)]
        public virtual DateTimeOffset? EndDatetime { get; set; }

        /// <summary>
        /// The searchable start date/time of the assets, in UTC (Formatted in RFC 3339)
        /// </summary>
        [JsonProperty("start_datetime", NullValueHandling = NullValueHandling.Ignore)]
        public virtual DateTimeOffset? StartDatetime { get; set; }

        [JsonProperty("updated", NullValueHandling = NullValueHandling.Ignore)]
        public virtual DateTimeOffset? Updated { get; set; }

        [JsonProperty("constellation", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string Constellation { get; set; }

        [JsonProperty("gsd", NullValueHandling = NullValueHandling.Ignore)]
        public virtual double? Gsd { get; set; }

        [JsonProperty("instruments", NullValueHandling = NullValueHandling.Ignore)]
        public virtual List<string> Instruments { get; set; }

        [JsonProperty("mission", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string Mission { get; set; }

        [JsonProperty("platform", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string Platform { get; set; }

        [JsonProperty("license", NullValueHandling = NullValueHandling.Ignore)]
        public virtual string License { get; set; }

        [JsonProperty("providers", NullValueHandling = NullValueHandling.Ignore)]
        public virtual List<Provider> Providers { get; set; }
    }

    public enum OrganizationRole { Host, Licensor, Processor, Producer };

    public enum StacItemType { Feature };


    public partial class StacItem
    {
        public static StacItem FromJson(string json) => JsonConvert.DeserializeObject<StacItem>(json, Deploy.LaunchPad.Core.STAC.StacItemConverter.Settings);
    }

    public static class SerializeStacItem
    {
        public static string ToJson(this StacItem self) => JsonConvert.SerializeObject(self, Deploy.LaunchPad.Core.STAC.StacItemConverter.Settings);
    }

    internal static class StacItemConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                OrganizationRoleConverter.Singleton,
                GeoJsonPointCoordinateConverter.Singleton,
                FluffyCoordinateConverter.Singleton,
                PurpleCoordinateConverter.Singleton,
                GeometryTypeConverter.Singleton,
                StacItemTypeConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }


    internal class StacItemTypeConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(StacItemType) || t == typeof(StacItemType?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "Feature")
            {
                return StacItemType.Feature;
            }
            throw new Exception("Cannot unmarshal type StacItemType");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (StacItemType)untypedValue;
            if (value == StacItemType.Feature)
            {
                serializer.Serialize(writer, "Feature");
                return;
            }
            throw new Exception("Cannot marshal type StacItemType");
        }

        public static readonly StacItemTypeConverter Singleton = new StacItemTypeConverter();
    }
}
