// Initially generated by quicktype https://github.com/quicktype/quicktype under the Apache 2 license.
//
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson
{
    public enum FeatureCollectionType { 
        FeatureCollection =0
    };

}
