// Initially generated by quicktype https://github.com/quicktype/quicktype under the Apache 2 license.
// 

using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson
{
    public partial struct FluffyCoordinate
    {
        public List<PurpleCoordinate> AnythingArray;
        public double? Double;

        public static implicit operator FluffyCoordinate(List<PurpleCoordinate> AnythingArray) => new FluffyCoordinate { AnythingArray = AnythingArray };
        public static implicit operator FluffyCoordinate(double Double) => new FluffyCoordinate { Double = Double };
    }


    internal class FluffyCoordinateConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(FluffyCoordinate) || t == typeof(FluffyCoordinate?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.Integer:
                case JsonToken.Float:
                    var doubleValue = serializer.Deserialize<double>(reader);
                    return new FluffyCoordinate { Double = doubleValue };
                case JsonToken.StartArray:
                    var arrayValue = serializer.Deserialize<List<PurpleCoordinate>>(reader);
                    return new FluffyCoordinate { AnythingArray = arrayValue };
            }
            throw new Exception("Cannot unmarshal type FluffyCoordinate");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            var value = (FluffyCoordinate)untypedValue;
            if (value.Double != null)
            {
                serializer.Serialize(writer, value.Double.Value);
                return;
            }
            if (value.AnythingArray != null)
            {
                serializer.Serialize(writer, value.AnythingArray);
                return;
            }
            throw new Exception("Cannot marshal type FluffyCoordinate");
        }

        public static readonly FluffyCoordinateConverter Singleton = new FluffyCoordinateConverter();
    }

}
