// Initially generated by quicktype https://github.com/quicktype/quicktype under the Apache 2 license.
// using the json schema found here: https://geojson.org/schema/GeoJSON.json
// 
using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson;
using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson.Types;
using System.Collections.Generic;

namespace Deploy.LaunchPad.Core.GeoJson
{
    public interface ICanBeDescribedInGeoJson<TGeoJsonType>
        where TGeoJsonType : IAmAGeoJsonType
    {
        TGeoJsonType Definition { get; set; }
        GeoJsonId? Id { get; set; }
    }
}