// Initially generated by quicktype https://github.com/quicktype/quicktype under the Apache 2 license.
// using the json schema found here: https://geojson.org/schema/GeoJSON.json
// 
using Deploy.LaunchPad.Core.Domain.Geospatial.GeoJson;
using System.Collections.Generic;

namespace Deploy.LaunchPad.Core.GeoJson
{
    public interface ICanBeDescribedInGeoJson
    {
        List<double> Bbox { get; set; }
        List<Geometry> Coordinates { get; set; }
        List<Feature> Features { get; set; }
        List<Geometry> Geometries { get; set; }
        Feature Geometry { get; set; }
        GeoJsonId? Id { get; set; }
        Dictionary<string, Geometry> Properties { get; set; }
        GeoJsonType Type { get; set; }
    }
}