using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a document set component generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class LaunchPadGeneratedDocumentSetComponent 
        : LaunchPadGeneratedComponent<LaunchPadGeneratedDocumentSetComponentConfiguration>
    {

        /// <summary>
        /// The list of folders that belong to this module.
        /// </summary>
        public virtual IDictionary<string, LaunchPadGeneratedFolder> Folders { get; set; }

        /// <summary>
        /// The list of documents that belong to this module.
        /// </summary>
        public virtual IDictionary<string, LaunchPadGeneratedDocument> Documents { get; set; }


        public LaunchPadGeneratedDocumentSetComponent() : base()
        {
            var comparer = StringComparer.OrdinalIgnoreCase;
            Folders = new Dictionary<string, LaunchPadGeneratedFolder>(comparer);
            Documents = new Dictionary<string, LaunchPadGeneratedDocument>(comparer);
        }
    }
}
