using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a static website component generated by LaunchPad Framework.
    /// </summary>    
    [Serializable]
    public partial class StaticWebComponent 
        : LaunchPadGeneratedComponent<StaticWebBlueprintDefinitionSettings, StaticWebBlueprintDefinitionInstructions>
    {

        /// <summary>
        /// The dictionary of static web pages that belong to this module.
        /// </summary>
        public virtual IDictionary<string, LaunchPadGeneratedStaticWebPage> StaticWebPages { get; set; }

        /// <summary>
        /// The dictionary of dynamicaly-generated stylesheets (LESS or SASS compiled into CSS) that belong to this module.
        /// </summary>
        public virtual IDictionary<string, LaunchPadGeneratedStylesheet> Stylesheets { get; set; }


        /// <summary>
        /// Returns a bool indicating if the component is currently in a valid or invalid state.
        /// </summary>
        /// <returns>True if the component is in a valid state, or false if it is contains missing or invalid elements.</returns>
        public override bool CheckValidity()
        {
            bool isValid = false;
            if (BlueprintDefinition != null
                && StaticWebPages != null && StaticWebPages.Count > 0
                && Stylesheets != null && Stylesheets.Count > 0
            )
            {
                isValid = true;
            }
            return isValid;
        }

        public StaticWebComponent() : base()
        {
            var comparer = StringComparer.OrdinalIgnoreCase;
            StaticWebPages = new Dictionary<string, LaunchPadGeneratedStaticWebPage>(comparer);
            Stylesheets = new Dictionary<string, LaunchPadGeneratedStylesheet>(comparer); 
        }
    }
}
