using System;
using System.Collections.Generic;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a solution generated by LaunchPad Framework which only contains static web resources.
    /// </summary>
    [Serializable]
    public partial class StaticWebSolution : LaunchPadGeneratedSolution
    {

        /// <summary>
        /// The set of generated static web resource modules that belong to this solution.
        /// </summary>
        public virtual IDictionary<string, StaticWebModule> Modules { get; set; }

        public StaticWebSolution() : base()
        {
            var comparer = StringComparer.OrdinalIgnoreCase;
            Modules = new Dictionary<string, StaticWebModule>(comparer);
        }
    }
}
