using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DeploySoftware.LaunchPad.Core.FileGeneration
{
    /// <summary>
    /// Represents a set of related static web pages or resources (.htm or CSS etc) generated by LaunchPad Framework.
    /// </summary>
    [Serializable]
    public partial class StaticWebModule :
        LaunchPadGeneratedModule<StaticWebModuleSettings>
    {
        public StaticWebComponent Website { get; set; }

        public StaticWebModule() : base()
        {
            Settings = new StaticWebModuleSettings();
            Website = new StaticWebComponent();
        }

    }
}
